### ISSUE TITLE
ArrayDisplay (in GroundFrame) to be fixed

### ISSUE THREAD

**Issue by thomasgas** [cta-observatory/ctapipe#1006]
While trying to analyse some data with a zenith of 60° for Paranal, I found a wrong behaviour in the ArrayDisplay:
![image](https://user-images.githubusercontent.com/24605557/54230258-5b932100-4506-11e9-8bcf-be7e4450203d.png)

Few considerations: 
- The reconstruction works (which is **good**) but the ArrayDisplay needs to be fixed.
- When you are in parallel mode, the plane of the camera and the TiltedGroundFrame are parallel and therefore you can use the angles obtained from the hillas parametrization to have the right plots, as shown here below.

![image](https://user-images.githubusercontent.com/24605557/54230128-12db6800-4506-11e9-9414-a877869fd82a.png)

In this screenshot from my 3D displayer you see the frame, positions of the telescopes, the lines using the angles from the hillas parametrization and the impact point (both MC & reco) for each plane:
- in green (tilted frame)
- in red (ground frame)

The problem is only related to the plotting in the ground frame; we can't use the same angles to draw the "hillas_line" in the GroundFrame since angles are not preserved when doing projections and therefore have to be recomputed to have a right plotting. 

This was correct until now since we've always used MC with a zenith equal to 20°, for which the difference between the angles in the TiltedGroundFrame and the GroundFrame is less than a couple of degree.

I'm working now to modify the ArrayDisplay in order to have the right angles and solve this issue (and also https://github.com/cta-observatory/ctapipe/issues/737).

**Comment by thomasgas** [comment]
I'm coming with a solution for this plotting. It works for Paranal, where the array is basically flat, 

![image](https://user-images.githubusercontent.com/24605557/54438893-f292ef80-4737-11e9-80f8-637876fcf8b9.png)

But not so well for La Palma (especially at high zenith). Here is an image obtained with a custom MC production done at az=150° and zen=60° for La Palma :

![image](https://user-images.githubusercontent.com/24605557/54439531-43571800-4739-11e9-8159-deccdf01bc2d.png)

In La Palma you can see that the angle is right now, but the line should be translated. The lines have the same z of the telescope whereas the impact point have z=0. 
So we can't just project them on the ground giving them a z=0 but they should be translated...it's difficult to explain 3d things just by writing :sweat_smile:

**Comment by thomasgas** [comment]
So i reprojected the positions of the telescopes in the ground frame from the tilted frame in order to make the lines passing through that point. It works:
![image](https://user-images.githubusercontent.com/24605557/54442741-7a302c80-473f-11e9-8450-9cd883d9c0ff.png)

**Comment by thomasgas** [comment]
Update: everything works in the tilted frame (reconstruction and ArrayDisplay):
```python
horizon_frame = AltAz()

array_pointing = SkyCoord(
    az=event.mc.az,
    alt=event.mc.alt, 
    frame=horizon_frame
)

fig, ax = plt.subplots(figsize=(10,10))

tilted_frame = TiltedGroundFrame(pointing_direction=array_pointing)

array = ArrayDisplay(
    event.inst.subarray.select_subarray(
        f'Paranal alt={array_pointing.alt:.2f}° az={array_pointing.az:.2f}°', hillas_dict.keys()
    ), 
    frame=tilted_frame,
    axes = ax)

#port the output of HillasReconstructor from Ground to Tilted
reco_core = GroundFrame(x=output.core_x, y = output.core_y, z = 0 * u.m)
reco_tilt = reco_core.transform_to(tilted_frame)
array.axes.scatter(reco_tilt.x, reco_tilt.y, c="r", label="reco", marker="+", s = 500)

#port the MC impact point from Ground to Tilted
mc_core = GroundFrame(x=event.mc.core_x, y = event.mc.core_y, z = 0 * u.m)
mc_tilt = mc_core.transform_to(tilted_frame)
array.axes.scatter(mc_tilt.x, mc_tilt.y, c="r", label="mc", marker="x", s = 500)

array.set_line_hillas(hillas_dict, range=1000)
array.add_labels()

array.axes.legend();
```
So that an event with 3 telescopes triggered gives this (in the tilted frame):
![image](https://user-images.githubusercontent.com/24605557/54691200-1f257d80-4b23-11e9-9834-243d3c36a738.png)
And this in the ground frame:
![image](https://user-images.githubusercontent.com/24605557/54691268-3b291f00-4b23-11e9-950a-a8de08334176.png)

**Comment by maxnoe** [comment]
@HealthyPear This is about the `psi_corr`, right? So it is fixed?

**Comment by HealthyPear** [comment]
Yes, I think this was fixed during my tests with protopipe.
