### ISSUE TITLE
Documentation Builds failing due to tornado upgrade

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1010]
Seems to be a problem with Tornado 6, while 5.1.1 works.  Tornado is needed by nbconvert which is used by sphinx to render the Jupyter notebooks in the documentation.

Tornado is not a ctapipe dependency, but perhaps we can make a hacky fix to this by adding a "conda install tornado=5.1.1" before the doc builds until they fix this.

**Comment by MaxNoe** [comment]
I fixed it by requiring nbconvert > 5.4 which works with tornado 6
