### ISSUE TITLE
Take pixel size from simtel, do not guess it

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1019]
Right now, we guess the pixel sizes from the given area.

Actually they are in the simtel file, we should just take those values.

```
In [1]: from eventio import SimTelFile                                                         

In [2]: f = SimTelFile('../data/chec.simtel.gz')                                               

In [3]: cam = f.telescope_descriptions[1]['camera_settings']['pixel_size']
                                  
```

**Comment by dneise** [comment]
just for my curiosity, is it clear what size means? Like inner circle radius?

**Comment by dneise** [comment]
But I agree we should avoid guessing.

**Comment by MaxNoe** [comment]
> just for my curiosity, is it clear what size means? Like inner circle radius?

According to the comment it is the diameter flat side to flat side for hexagons and edge size for square.

**Comment by maxnoe** [comment]
As discussed in the PR, we are not really guessing but *calculating* from well defined inputs to well-defined outputs. So no reason to store duplicated info.
