### ISSUE TITLE
Add observatory location to SubarrayDescription

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1031]
the SubarrayDescription (built currently in each EventSource) should contain the location of the observatory as an `astropy.coordintates.EarthLocation`.  This is needed e.g. for some coordinate transforms.

I suggest we add it as a field called "location", so we can do things like:
```py3
subarray = SubarrayDescription(...)
elevation = subarray.location.height
# <Quantity 2124. m>
```

**Comment by maxnoe** [comment]
Done in #1980
