### ISSUE TITLE
TelescopeDescription string representation changed

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1058]
Old behavior:
```py3
>>> str(sub.tel[410])
'SST-1m:Digicam'
>>> str(sub[tel][100])
'SST-ASTRI:AstriCam'
```

Current Behavior:
```py3
>>> str(sub.tel[410])
'1m:DigiCam'
>>> str(sub[tel][100])
'ASTRI:AstriCam'
```

Seems the telescope type is no longer prepended. Since the full telescope identifier is used for output table naming, this causes some problems since a variable name that starts with a number (like `1m`) is forbidden.  Could we go back to the old behavior? Any objections?

**Comment by kosack** [comment]
Another thing to discuss is to have these output "allowable" variable/column names, e.g:
`SST_1m_DigiCam`. The main issue there is that for optics types with no subtype (e.g. LST), is it better to get `LST_LSTCam` or `LST__LSTCam`? (in case somebody wants to split on `_` rather than lookup the details in the instrument description)

**Comment by MaxNoe** [comment]
or `LST_LST_LSTCam`? :D

Also, why is it `LSTCam`, isn't it called `DragonCam`?

**Comment by kosack** [comment]
>or LST_LST_LSTCam?

The name of the sub-type isn't really "LST" though, right? I guess in the real future, we'll have to think about versions of the structure, if after the prototypes, it changes. I guess it could be `<tel class>_<optics_type>_<camera>: LST_Prototype_LSTCam` (same for `MST_Prototype_NectarCam`, `SST_1m_Digicam`, `SST_ASTRI_CHEC`, etc.)

>Also, why is it LSTCam, isn't it called DragonCam?
Yes, could be also a good time to rename it - I think at the time the code was originally written, I didn't know the name, so called it LSTCam.

**Comment by kosack** [comment]
There's also the fact that we have CHEC-M and CHEC-S cameras, so perhaps also having a camera subtype could be useful

**Comment by GernotMaier** [comment]
Plus for prod4-SST we simulated GCT-S with 6.2 mm and with 7 mm pixels. So this should be as flexible as possible.

**Comment by kosack** [comment]
> Plus for prod4-SST we simulated GCT-S with 6.2 mm and with 7 mm pixels. So this should be as flexible as possible.

Yes, we need to have version numbers inside the optics description.  Since those don't change within a prod, it's ok to not have that info in the string representation (which is so far just used to name output tables for DL1 and to name Machine Learning models).  Having the "prod" identifier somewhere more globally (like in the SubarrayDescription or the mcheader) would also be very useful.

**Comment by MaxNoe** [comment]
Maybe we should aks conrad to wwrite the production info into the `target` of the run header?

RIght now, this is `Monte Carlo Beach`, which is not that helpfull :rofl:

**Comment by bregeon** [comment]
> Yes, we need to have version numbers inside the optics description. Since those don't change within a prod, it's ok to not have that info in the string representation (which is so far just used to name output tables for DL1 and to name Machine Learning models). Having the "prod" identifier somewhere more globally (like in the SubarrayDescription or the mcheader) would also be very useful.

I agree on that, we do not need to be that flexible on these column names, the corresponding exact hardware configuration will be stored elsewhere, we just need minimal information here for convenience.
