### ISSUE TITLE
Several tools require seekable event sources

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#1063]
I think this is unecessary. 
This tools should simply check if an event source is seekable or not, and then either provide or not provide the possibility to go backwards.

**Comment by kosack** [comment]
see #1076  - they should still be able to forward-seek, I think. Backward is optional.

**Comment by kosack** [comment]
In the case of a source that can't seek backward, a GUI could for example just disable the "back event" button, or implement a local event buffer if it's needed.
