### ISSUE TITLE
EventSeeker str vs int

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#1064]
I think the API of the EventSeeker is not ideal. That integers mean lookup by index and str mean lookup by event id.

Pandas uses `loc` and `iloc` accessors to differentiate the two.

We could use `.idx` and `.eventid` accessors.

Opinions?

**Comment by watsonjj** [comment]
I would support that. It's more explicit.

**Comment by dneise** [comment]
I mentioned this already at the meeting in dortmund... and I'd like to mention it again, although it is embarrassing:

So I had a problem understanding the difference between the terms "index" and "id". I must admit up to then I lived in a world where "id" was simply an abbreviation for the word "index", but I learned this is not the case: "id" is an abbreviation for "(unique) identifier". 

Anyway I still have a hard time understanding which is which. I might be the only person having this problem ... or I might not, so I looked up the definitions of the words again ... in wikipedia ... not sure this is the right place:
 * https://en.wikipedia.org/wiki/ID
 * https://en.wikipedia.org/wiki/Index

So ... ["ID"](https://en.wikipedia.org/wiki/ID) is `Identifier, a symbol which uniquely identifies an object or record` ... can be any symbol .. 
while ["Index"](https://en.wikipedia.org/wiki/Index) (scroll down to "computer science")  is either:
1.) `Index, a key in an associative array` or
2.) `Array index, an integer pointer into an array data structure`

So ... I believe one of the definitions for "index" from wikipedia ("key in an associative array") is pretty close to the definition of "ID"... so maybe it is not only me having this problem. 

Therefore I wanted to ask again ... could we find names which are more clear here? Or at least write down our definitions of "id" and "index" somewhere in (several) obvious locations?

**Comment by dneise** [comment]
So .. at the moment the definition of `id` vs `index` can e.g. be found here. 
https://github.com/cta-observatory/ctapipe/blob/master/ctapipe/io/eventseeker.py#L46

But I assume this concept of having both `id` and `index` is more fundamental than the `EventSeeker` in fact it is a cta wide concept, no?

**Comment by MaxNoe** [comment]
> But I assume this concept of having both id and index is more fundamental than the EventSeeker in fact it is a cta wide concept, no?

It's more. It's a general problem whenever you have some kind of ordered data with an id, or in database speak, a `PrimaryKey`.

You can have a collection of such things, and you immediately have the problem, that you sometimes want to access things by the position in the collection and sometimes by the `Primary Key`, e.g. event_id or something else.

**Comment by dneise** [comment]
Okay, so maybe we could just borrow the exact same terminology and call the accessors: `loc` and `iloc` instead of `idx` and `id`.

**Comment by MaxNoe** [comment]
Yes we could, but we could make it more explicit by giving the accessors names that speak more.

**Comment by dneise** [comment]
Ah so even `.by_position` and `.by_label` ?

**Comment by MaxNoe** [comment]
I would call it `event_id` as this is the variable we use to make the lookup. The data container has members `obs_id` and `event_id`.

**Comment by kosack** [comment]
I support this proposal.  I suppose I prefer: `seeker.event_id[12345]` and `seeker.event_index[12]` since they are the most clear.

**Comment by kosack** [comment]
The only possibly reason we might want to have an array-like interface would be to allow complex indexing and slicing, like:
```py3
events = seeker.event_id[[1,15,17,23]]
events = seeker.event_index[30:40]
```
If we don't support that, then we should just stick with methods.
