### ISSUE TITLE
 Profiling tool, suggestions?

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/ctapipe#1086]
Hi, 
I would like to profile the camera calibration code.
Do you suggest some specific tool?

Thanks

**Comment by vuillaut** [comment]
Hi @FrancaCassol 
By profiling, you mean computing-wise?
If so, I would suggest cProfile for the profiling and snakeviz for the visualisation of the results.

**Comment by FrancaCassol** [comment]
I mean, I would like to see where are the weak parts of the code in terms of running time (if any ;-) )
Ok, I will have a look at these tools. Thanks

**Comment by vuillaut** [comment]
Yep that's what you are looking for.
