### ISSUE TITLE
ctapipe-extra on detached branch

### ISSUE THREAD

**Issue by jacquemier** [cta-observatory/ctapipe#109]
when following  [installation procedure](https://cta-observatory.github.io/ctapipe/getting_started/index.html), submodule ctapipe-extra branch is detached: 

```
(cta_test)>git branch 
* (HEAD detached at 536490d)
  master
```
I need to execute a "git checkout master" to switch to branch before running tests to obtain all datafiles.
If I did not make any mistake, we need to update documentation.

**Comment by jacquemier** [comment]
Or, rather than change documentation, we can change init target of main Makefile to add git checkout master command

**Comment by mackaiver** [comment]
I guess with ctapipe-extra being a module we can close this now right?

**Comment by jacquemier** [comment]
I agree
