### ISSUE TITLE
Getting uncertainties on time gradient and intercept in timing_parameters

### ISSUE THREAD

**Issue by andres-baquero** [cta-observatory/ctapipe#1100]
Hi, I'm triying to get the uncertainties of time gradient and intercept for using in RF for reconstruction.

I understand that in numpy.polynomial.polynomial.polyfit function  the parameter singular_values returns the singular values of the scaled Vandermonde matrix, with contains the uncertainties, in this case for intercept and slope (time gradient). But now I'm getting just a matrix of [1. 1.].  And this matrix Vandermonde must be of 2x2.

Which is the best way of doing it?

Thank you.

**Comment by MaxNoe** [comment]
You could use `numpy.polynomial.Polynomial.fit`.

polyfit is deprecated anyways.

**Comment by MaxNoe** [comment]
You could use https://en.wikipedia.org/wiki/Weighted_least_squares

Also: maybe the uncertainties on the parameters are interesting, but also the sum / max / min of the residuals could be very helpful

**Comment by MaxNoe** [comment]
Fixed by merging #1101
