### ISSUE TITLE
writing string with HDF5TableWriter

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/ctapipe#1116]
How can I write string fields with `HDF5TableWriter`?

```
In [1]: from ctapipe.io.containers import Container, Field
   ...: from ctapipe.io import HDF5TableReader, HDF5TableWriter
   ...:
   ...: class TextContainer(Container):
   ...:     text = Field("hello", "some text")
   ...:     number = Field(int, "some number")
   ...:
   ...: text_container = TextContainer()
   ...: text_container.text = 'bonjour'
   ...: text_container.number = 2
   ...:
   ...: with HDF5TableWriter('testfile.h5', group_name='data') as writer:
   ...:     writer.write('text', [text_container])
   ...:
   ...: with HDF5TableReader('testfile.h5') as reader:
   ...:     tab = reader.read('/data/text', TextContainer())
   ...:     new_text_container = next(tab)
   ...:
   ...: new_text_container.text
Table '/data/text' is missing column 'text' that is in container TextContainer. It will be skipped.
Out[1]: 'hello'
```

**Comment by kosack** [comment]
Can you give a use case? I can't really image a place where you want to write strings to the binary file, other than in headers. You can use an ENUM to convert most strings to integer keys. 

The answer so far though is that strings are not currently supported but we could add it.  I would caution against allowing variable-length strings, though, since that causes a large speed decrease since they can't be stored contiguously with the rows.

**Comment by kosack** [comment]
see for example: https://cta-observatory.github.io/ctapipe/examples/containers_with_enums_and_table_writer.html

**Comment by vuillaut** [comment]
Yes actually I might be trying to write information at the wrong place... 

The use case is basically provenance: writing info about used source files, algorithms, etc...
Note that I also would like to be able to merge files and thus a table seemed like a good idea, so I can keep track of each line for each file.

**Comment by vuillaut** [comment]
Note2: in my first implementation, I went for `root._v_attrs` but then I'm not leveraging on HDF5TableWriter and Containers and it I have to add some custom code.

**Comment by kosack** [comment]
Those should be in the metadata, any `Container` class has a `.meta` attribute which is a dictionary.  Anything you put in there is written to the HDF5 attributes of that dataset

**Comment by kosack** [comment]
Note that it is written the first time `writer.write()`  is called, while it is constructing the table (you can only write the headers once), so make sure you define what you want in `container.meta` first before writing any rows out

**Comment by kosack** [comment]
Also note that some attributes are written automatically by HDF5TableWriter, such as units and the ctapipe version:

![image](https://user-images.githubusercontent.com/11677812/62470833-93438380-b79b-11e9-9b7c-4b9f8d92ce91.png)

**Comment by kosack** [comment]
> Note2: in my first implementation, I went for root._v_attrs but then I'm not leveraging on HDF5TableWriter and Containers and it I have to add some custom code.

I think that's ok, since `HDF5TableWriter` is not meant to be a general data manager, just the part that deals with a single dataset in a file, it shouldn't get overloaded with too much functionality. We eventually will need to build some helper functions or a class for managing groups of datasets and metadata inside a file.

**Comment by MaxNoe** [comment]
The container contains the default value if no value could be read? That is dangerous right?

**Comment by kosack** [comment]
> The container contains the default value if no value could be read? That is dangerous right?

I guess that is unrelated to this issue, but still a problem.  Perhaps open another issue.  I guess it's ok if the defaults are nan, or it should write nan or None to the output field in that case.

**Comment by MaxNoe** [comment]
PyTables still does not support variable length strings.
So we could only use fixed length strings with e.g. setting a size in `Field`, which would be related to #1224 or use the length of the first element and warn if a string gets truncated.

**Comment by maxnoe** [comment]
This is now implemented using a `max_length` either given to the field or from the first element written in #1817
