### ISSUE TITLE
Improve recognition for contributions

### ISSUE THREAD

**Issue by watsonjj** [cta-observatory/ctapipe#1149]
Recognition for activity and contributions to ctapipe is something that could be improved upon in at least two ways:

1. Use zenodo to get a DOI (#678)
2. Utilise Github's CODEOWNERS functionality (#569)

Both of these were suggested in previous issues.

More on codeowners:

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

I don't recommend activating the **requiring** a review from a code owner for a PR to be accepted - I don't think this would be productive for us. But being able to see who is responsible for maintaining particular code could be helpful

**Comment by kosack** [comment]
added DOI and codeowners (see #1150  and #1151)
