### ISSUE TITLE
Proposal: require "black" code formatter as pre-commit hook

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1159]
To avoid style change problems, I suggest we require devs to either manually run "black" (or in their editor of choice), or install it as a pre-commit hook (see e.g. https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/)

Black Documentation: https://black.readthedocs.io/en/stable/index.html

For bits of code where black really does a worse job (are there any?), I think it can be disabled explicitly similar to yapf's `# yapf: disable`

Edit: actually it's `# fmt: off` and end with `# fmt: on`.

**Comment by watsonjj** [comment]
Do we also adopt the 88 character line length?

**Comment by kosack** [comment]
It's ok with me - I already have the tests only check for 90 I think, even though we recommend 80.  The idea of 88 is just that you should normally stick to 80, but it's ok to go over a bit in cases where it makes sense.  The alternative is to specify it in a config file, so black uses 80.

**Comment by vuillaut** [comment]
To be considered:
https://github.com/marketplace/actions/black-code-formatter

**Comment by kosack** [comment]
How does that work? Does it modify the code when you push? Wouldn't that create conflicts? Or does it just warn that the user didn't run black?

**Comment by kosack** [comment]
Ah I see it just uses the --check option, so might be a good idea ! I guess it's like a harsher version of what codacy is already doing with its pep8 checking, but also applying to actual formatting.

**Comment by MaxNoe** [comment]
done
