### ISSUE TITLE
GroundFrame directions

### ISSUE THREAD

**Issue by nbiederbeck** [cta-observatory/ctapipe#1183]
What are the x-, y-, (z-) directions of `ctapipe.coordinates.GroundFrame`?

In MAGIC it is
```
x = north
y = west
```

what about CTApipe?

**Comment by thomasgas** [comment]
In ctapipe it is the same as in MAGIC

**Comment by kosack** [comment]
and I think so far Z is meters above the array center (not meters above sea-level)

**Comment by thomasgas** [comment]
> and I think so far Z is meters above the array center (not meters above sea-level)

z is in meters above the array observation level which is saved in ``event.mcheader.prod_site_alt``

**Comment by MaxNoe** [comment]
It should be noted that this is different from the cartesian representation of astropy AltAz coordinates.

This could bite us, right?

**Comment by MaxNoe** [comment]
```
In [3]: AltAz(alt='0d', az='0d').cartesian                                                                                                    
Out[3]: 
<CartesianRepresentation (x, y, z) [dimensionless]
    (1., 0., 0.)>

In [4]: AltAz(alt='90d', az='0d').cartesian                                                                                                   
Out[4]: 
<CartesianRepresentation (x, y, z) [dimensionless]
    (6.123234e-17, 0., 1.)>

In [5]: AltAz(alt='0d', az='90d').cartesian                                                                                                   
Out[5]: 
<CartesianRepresentation (x, y, z) [dimensionless]
    (6.123234e-17, 1., 0.)>


```

So in astropy 0d az = N = x, 90d az = E = y

**Comment by maxnoe** [comment]
This is now documented in the `GroundFrame` docstring and we added `NorthingEastingFrame` for easier map plotting.

I think this can be closed.
