### ISSUE TITLE
Use notebook review tool?

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#1198]
Just stumbled upon this, might be worth using for our documentation notebooks:
https://github.com/marketplace/review-notebook-app

**Comment by dneise** [comment]
regarding the notebook-git workflow do you guys have any recommendations? Do you nowadays check in notebooks with content or without? And how do you deal on your local machines with the annoying fact, that notebooks once they were executed locally are shown as modified ... is there any silver lining regarding notebooks and git?

**Comment by vuillaut** [comment]
I thought the "rule" was to `nbstripout` the notebooks before to submit so the output is not there but only the modified code appears as modified.
The review notebook app might still be useful :)

**Comment by kosack** [comment]
> check in notebooks with content or without

Yes, the idea is you must strip the content - it is then generated when the docs are built by `nbsphinx`, so that we can test for errors.

**Comment by kosack** [comment]
Let's try this review tool! I just have to figure out how to install it in the cta-observatory project - When I try via the link, it only gives access to my local repos.

**Comment by kosack** [comment]
added
