### ISSUE TITLE
what does this line do?

### ISSUE THREAD

**Issue by dneise** [cta-observatory/ctapipe#1202]
https://github.com/cta-observatory/ctapipe/blob/608c938a29930c1c6bd603b2c702e4ef39ae1a7c/ctapipe/core/traits.py#L261

seems to be the only occurrence of `klass` in ctapipe ...

**Comment by watsonjj** [comment]
https://github.com/cta-observatory/ctapipe/pull/1158#discussion_r340089950

**Comment by dneise** [comment]
Ah thanks

**Comment by kosack** [comment]
may be good to add a comment to that line, so we don't get confused in the future and delete it.
