### ISSUE TITLE
clean up circular dependencies

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1205]
Using `pydeps`, I found a few places where we have some circular imports that should probably be removed:

![ctapipe](https://user-images.githubusercontent.com/11677812/70634421-7da30680-1c32-11ea-90cc-50b6578fdd35.png)

**Comment by watsonjj** [comment]
Possibly related to #1037

**Comment by watsonjj** [comment]
Some refactoring was performed in #1267 to fix some of the circular dependencies

**Comment by MaxNoe** [comment]
Yes, I can think we can close this for now. #1267 seems to have fixed most issues with this.
