### ISSUE TITLE
Tools should give a reasonable return value to the shell

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1214]
Right now in `ctapipe.core.Tool.run()` different types of errors are caught and the activity status in the Provenance are updated.  However, there are no return values: it should also return 0 on success, and a standard error code if not (See e.g. http://tldp.org/LDP/abs/html/exitcodes.html)

See also: https://github.com/cta-observatory/cta-lstchain/issues/271

**Comment by kosack** [comment]
relevant code to modify is here: https://github.com/cta-observatory/ctapipe/blob/12d768d05f6cd279e5b31476da5ae6c9697af437/ctapipe/core/tool.py#L200-L230

**Comment by MaxNoe** [comment]
Wasn't this already solved by @dneise? In connections with tool tests failing unnoticed?

I think this is it: https://github.com/cta-observatory/ctapipe/pulls/pull/1027

**Comment by kosack** [comment]
Ah, that's good - I think that PR was broken for a while, so got forgotten.  Perhaps we can just get #1027  working and close this then
