### ISSUE TITLE
master build is failing in test_array_display

### ISSUE THREAD

**Issue by watsonjj** [cta-observatory/ctapipe#1229]

**Comment by MaxNoe** [comment]
due to matplotlib 3.2?

**Comment by MaxNoe** [comment]
Can confirm that this is a breaking change between matplotlib 3.1 and 3.2

**Comment by MaxNoe** [comment]
https://github.com/matplotlib/matplotlib/issues/16743

**Comment by watsonjj** [comment]
Shall we limit the maximum version of matplotlib to 3.1 for the time being?

**Comment by watsonjj** [comment]
Or skip the test for now?
