### ISSUE TITLE
Curiously little references 

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1266]
For a rather large scientific codebase, the number of references cited in docs/bibliography.rst is rather small.

I would urge everyone who authored code here to check if relevant references are given in the docstrings of respective methods.

@cta-observatory/ctapipe-core-devs

**Comment by MaxNoe** [comment]
Maybe we should add https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html to make it easier to cite stuff?

**Comment by kosack** [comment]
yes that would be great. It would also make it easier to cite reference in papers, since one could just import the bib file.
