### ISSUE TITLE
Make `is_simulated` a property of the event source

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#1286]
I think this is important information that should not be hidden in `metadata` and be required to be implemented for all event sources.

Opinions?

**Comment by vuillaut** [comment]
I agree.

**Comment by watsonjj** [comment]
I have nothing against it. But we only really have one simulation source, so its quite clear already. Did you encounter a particular need for this information, other than for "metadata" reasons?

**Comment by MaxNoe** [comment]
I don't really wanne see `isinstance(event_source, SimTelEventSource)` when it could be
`if event_source.is_simulated`.

**Comment by watsonjj** [comment]
But what follows that `if` statement that is guaranteed to be valid for any simulation event source?

**Comment by MaxNoe** [comment]
Yes, e.g. writing the mc container to the DL1 file.

**Comment by watsonjj** [comment]
Okay, that sounds valid (assuming any simulation event source is guaranteed to have implemented that container)

**Comment by kosack** [comment]
Sounds good to me.  You might also want some other meta info like what data level the event source provides. 

```py3
print(eventsource.is_simulated).
print(eventsource.data_levels) 
```
```
True
['R0', 'R1']
```


Where eventsource.data_level is a list of what data levels are generated: 
*  `["DL1",]` for a DL1EventSource, when that exists
*  `["R0","R1"]` for SimTelEventSource

**Comment by MaxNoe** [comment]
@kosack that's a good idea, will include that
