### ISSUE TITLE
Is enum_trait duplication from `TypeTrait`?

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#1289]
It seems to me, that our `enum_trait` function is a duplication of traitlets buildin `Type`. 

https://traitlets.readthedocs.io/en/stable/trait_types.html#traitlets.Type

Is there a reason why this was reimplemented? Or did we just overlook the `Type` trait?

**Comment by watsonjj** [comment]
Does it also detect subclasses of subclasses (etc.)? That is the special thing provided by `non_abstract_children`

**Comment by watsonjj** [comment]
Also does it detect if the subclass is abstract?

**Comment by MaxNoe** [comment]
So it doesn't offer options at all. It just makes sure whatever is given is a a subclass of the given klass.

And you have to give the fully qualified name.


I'll close this, as the enum thing is clearly superior for us.
