### ISSUE TITLE
Divide by zero in hillas parameters

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#1327]
During running the dl1 tool I noticed a divide by 0 error in the hillas parameters when calculating psi.

This should not happen, as the angle can still be well defined for `x = 0` if `y != 0`

**Comment by MaxNoe** [comment]
Okay, the result is still correct though:

``` 
In [4]: np.arctan(np.inf)                                                                                                                     
Out[4]: 1.5707963267948966
```

so it would just be getting rid of the warning, which is not critical I think

**Comment by kosack** [comment]
We could filter the warning, so users aren't confused. Warnings should mean something, if not people ignore all of them.
