### ISSUE TITLE
Replace custom version with setuptools_scm

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1333]
There is an extension for setuptools, which provides the functionality we need and which 
integrates nicely with the build system requirements handled by pyproject.toml.

Astropy is are also using this:
https://github.com/astropy/astropy/blob/master/pyproject.toml

**Comment by kosack** [comment]
can you explain what this does and if it really replaces what we use? There was a lot of tweaking to get the current system to work correctly with the conda builds, etc, so I would like to avoid changing this until the next version.
