### ISSUE TITLE
Performance regression tests

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#1362]
I think we should start thinking about defining some performance regression tests and how we can execute them.

I searched a bit around but have not yet found a nice way to do this.

Anyone else have experience with this?

This is purely concerned with speed, not physics performance.

**Comment by kosack** [comment]
See also issue #1109

CI systems are really not intended for performance testing, since you need to store history and compare over time, but perhaps we can find a good open-source performance monitoring system? I know some exist

**Comment by kosack** [comment]
closing since this is a duplicate
