### ISSUE TITLE
Saving a camera geometry to hdf5 does not store pixel shape

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1384]
There is no info about pixel shape in the hdf5 files written by the stage1 tool.

**Comment by MaxNoe** [comment]
![Screenshot_20200717_110611](https://user-images.githubusercontent.com/5488440/87769183-8c334b00-c81d-11ea-9391-3f578ef088ab.png)

**Comment by maxnoe** [comment]
Turns out it is currently stored using the astropy metadata tables.

So this is a non-issue and somewhat a duplicate of #1449
