### ISSUE TITLE
create one instance of the tests with `NUMBA_DISABLE_JIT=1` for the coverage report?

### ISSUE THREAD

**Issue by dneise** [cta-observatory/ctapipe#1400]
Side point: numba jitted functions do not contribute to coverage, we might want to create one instance of the tests with `NUMBA_DISABLE_JIT=1` for the coverage report.

_Originally posted by @MaxNoe in https://github.com/cta-observatory/ctapipe/pull/1398#issuecomment-662900445_

**Comment by maxnoe** [comment]
Unfortunately, as e.g. guvectorize functions don't work in pure python mode.

How to handle coverage with numba is an open issue with them, and I fear we just need to wait until something is implemented in numba itself.
