### ISSUE TITLE
black pre-commit hook in documentation

### ISSUE THREAD

**Issue by nbiederbeck** [cta-observatory/ctapipe#1410]
I stumbled across the pre-commit hook for black in #1345.

I could not find any other mention of this. I suggest we add this somewhere in the [Getting Started For Developers](https://cta-observatory.github.io/ctapipe/getting_started/index.html#getting-started-for-developers) guide. Either:

* as a last [`get-the-ctapipe-software` step](https://cta-observatory.github.io/ctapipe/getting_started/index.html#get-the-ctapipe-software); or 
* as a first [`developing-a-new-feature-or-code-change` step](https://cta-observatory.github.io/ctapipe/getting_started/index.html#developing-a-new-feature-or-code-change)

In the same run we can think of adapting the [coding style guide](https://cta-observatory.github.io/ctapipe/development/style-guide.html#coding-style) which suggests following PEP8, which is not *really* necessary with the pre-commit hook.

Thoughts?

**Comment by maxnoe** [comment]
Yes please, could you do that?

**Comment by nbiederbeck** [comment]
PR: #1488

**Comment by maxnoe** [comment]
You can link PRs in the panel on the right side ;)

**Comment by HealthyPear** [comment]
I stumbled also upon this...

I was thinking, wouldn't be easier to use the hook directly into the CI?
It is explained [here](https://pre-commit.com/#github-actions-example), so that the developer doesn't even need to worry about setting this up?

**Comment by kosack** [comment]
Sure, maybe open a PR?
