### ISSUE TITLE
Match telescope descriptions and camera descriptions by an index, not by name

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1424]
We should save an additional table where we store for each telescope id, the index for the camera description and the optics description.

At the moment, we assume that the `tel_description` string is unique.
But this is not the case for simulations of the LST / MAGIC array since there, the two MAGIC telescopes differ only in mirror area.

This is currently not possible and reading back the instrument description will not yield the correct result.

**Comment by MaxNoe** [comment]
I think we assume this in quite a lot of places. But I think this is really an anti-pattern.

We rely on something that comes from the `guessing` part of the names rather than on something well-defined like telescope ids and indices.

To be safe, we could just store everything by telescope_id, which would be a bit larger, but ultimately the safe bet.

**Comment by MaxNoe** [comment]
Example:

```
In [3]: s = SimTelEventSource('/fefs/aswg/workspace/MC_common/corsika7.7_simtelarray_20200629/prod5/4LSTs_MAGIC/gamma/zenith_20deg/south_point
   ...: ing/sim_telarray/off0.4deg/data/gamma_20deg_180deg_run1___cta-prod5-lapalma_4LSTs_MAGIC_desert-2158m_4LSTs_MAGIC_mono_off0.4.simtel.gz
   ...: ')                                                                                                                                    

In [4]: s.subarray.to_hdf('test.hdf5')                                                                                                        

In [5]: s2 = s.subarray.from_hdf('test.hdf5')                                                                                                 

In [6]: s2 == s                                                                                                                               
Out[6]: False
```

**Comment by MaxNoe** [comment]
An alternative would be to include mirror area and and/or `num_mirror_tiles` in the guessing, but like I said, I don't like relying on the guessing at all.

It also makes it impossible match the telescopes without the guessing code inside ctapipe, which is also a nogo, I think.
