### ISSUE TITLE
Number of simulated events seems to be a factor of two off

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#1434]
At least for the signal

**Comment by MaxNoe** [comment]
The number of events surviving cuts is very similar for both chains, ~1.3 Million.

The effective area of pyirf is a factor of two larger:

![effarea](https://user-images.githubusercontent.com/5488440/94719476-7da3fc80-0353-11eb-983e-de32761cccad.png)


This means that the number of simulated events seems to be a factor of two off (too few events)

**Comment by LukasNickel** [comment]
https://github.com/cta-observatory/pyirf/pull/80

**Comment by MaxNoe** [comment]
Fixed

**Comment by MaxNoe** [comment]
And wrong repo, sorry
