### ISSUE TITLE
twopass extractor charge resolution broken in v0.9.0

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1441]
@HealthyPear found that the Charge Resolution benchmark no longer passes, see below.  

Seems to be a bug introduced in either #1356 or possibly, but less likely, #1370 

For ctapipe 0.8.0:
![RMS_08_LST](https://user-images.githubusercontent.com/11677812/95078917-2cf71f80-0716-11eb-9440-0efe227ff6b8.png)

For ctapipe 0.9.0:
![RMS_09_LST](https://user-images.githubusercontent.com/11677812/95079101-747dab80-0716-11eb-9ef0-df9863c079a5.png)

**Comment by kosack** [comment]
Note the problem occurs in the first pass of the TwoPass method, so is likely something simple and not related to the time fitting (which hasn't run at this point in the benchmark)

**Comment by HealthyPear** [comment]
also, nevermind the requirement, is not in the same units...I have to remember to disable it for the time being...

**Comment by kosack** [comment]
I think the problem is just in the definition of the windows and shifts. With the current version, there was a misunderstanding on the definition and it should miss the peak in many cases - working on a fix.
