### ISSUE TITLE
CameraReadout.to_table is not FITS compatible

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1452]
`CameraReadout.to_table().write("readout.fits")` creates a HIERARC keyword in the output FITS file, since the `REF_WIDTH` header is > 8 characters.  Suggest changing it to `REFWIDTH`.   Or we just deal with the strange data model (it's fine for other formats like HDF5 and ECSV, just not FITS).

**Comment by maxnoe** [comment]
Let's use REFWIDTH. I think it was meant to be fits compatible but miscounted, otherwise a more explicit name would have been appropriate.
