### ISSUE TITLE
developer install currently broken on macOS

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1497]
Using a clean install of miniconda (or anaconda), and following the install instructions fails for both python 3.7 and 3.8 with an error of `Found conflicts! Looking for incompatible packages.`.   Seems there is a missing package or too-strict dependency somewhere for macOS, since this works fine for Linux. 

We used to test installs on macOS in Travis - why did that stop?

### steps to reproduce:

```bash
PYTHON_VERSION=3.7 sed -i -e "s/- python=.*/- python=$PYTHON_VERSION/g" environment.yml
conda env create -n ctadev --file environment.yml
```

**Comment by maxnoe** [comment]
At some point the build did not work and we removed it.

**Comment by kosack** [comment]
> At some point the build did not work and we removed it.

since many of the devs (myself included) use macOS, we should think about fixing that.

**Comment by kosack** [comment]
Seems simply adding conda-forge to the channel list fixes it.  So I guess using `- conda-forge::<PACKAGE>` tries to get a single package from conda-forge, but not its dependencies

**Comment by maxnoe** [comment]
@kosack that seems to be it.

By the way, I learned today that astropy imports their conda-forge packages to the astropy namespace, so that people don't have to solve vs. the full conda forge.

We could do the same.

**Comment by maxnoe** [comment]
Wenn we add the `conda-forge` channel, now suddenly everything comes from forge. Do we want that?

**Comment by kosack** [comment]
> By the way, I learned today that astropy imports their conda-forge packages to the astropy namespace, so that people don't have to solve vs. the full conda forge.

That's an option, since requiring everything from conda-forge is maybe not the best idea.  It means some more maintenance for us though, since I guess they have to move packages to their channel.

There must be some way to keep the basic packages in `defaults` like numpy MKL, and still use a few packages from conda-forge. Not sure why the deps are so restrictive now.

**Comment by maxnoe** [comment]
For now you can probably simply add `conda-forge::corsikaio`, does that solve you problem?

**Comment by maxnoe** [comment]
I think this was fixed? @kosack can you confirm?
