### ISSUE TITLE
Make sure tools can work with dl1 input

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1505]
Now that we have the DL1 event source, we should make sure that the existing tools can actually use it.

Most importantly:

- [ ] display_dl1
- [ ] stage1 (images to parameters in case only images were saved)
- [ ] muon_reconstruction

**Comment by LukasNickel** [comment]
I think these cases are actually all working and tested now.
The muon reconstruction is getting reworked, but should keep that functionality.
Should we close this?
