### ISSUE TITLE
test_event_source_config looks broken to me.

### ISSUE THREAD

**Issue by dneise** [cta-observatory/ctapipe#1517]
There is a test ` def test_event_source_config(): ` in `ctapipe/io/tests/test_event_source.py`  
(and the one below) which seems broken to me. They use two identical strings to see if the config overwrites the `input_url` or the other way around.

_Originally posted by @dneise in https://github.com/cta-observatory/ctapipe/pull/1515#discussion_r523911616_

**Comment by maxnoe** [comment]
Furthermore, the test is completely identical to the test just below.
