### ISSUE TITLE
More code removals

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1527]
1. [ ] https://github.com/cta-observatory/ctapipe/blob/master/ctapipe/io/array.py seems not to be used anywhere, has no tests and is probably superseeded by `SubarrayDescription.from_hdf / to_table / ...` 
2. [ ] https://github.com/cta-observatory/ctapipe/blob/master/ctapipe/io/files.py Not used, has a test, but uses IMHO the wrong approach, instead of looking at the actual file contents and checking for magic bytes, it just uses file extension. Also there are very well tested libraries we could use if we really needs this kind of functionality. Mostly stuff like this is implemented in `EventSource.is_compatible` implementations

**Comment by kosack** [comment]
that's a leftover from the past before there was an instrument module - can remove it safely.

**Comment by kosack** [comment]
agreed, remove files as well (another remnant)
