### ISSUE TITLE
Tools do not log traceback on exceptions

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1528]
For some reason, although `Tool` uses

```
            self.log.exception(f"Caught unexpected exception: {err}")
```

No traceback is logged when an exception  occurs.

**Comment by kosack** [comment]
might need to add `exc_info=True` to the call

**Comment by maxnoe** [comment]
No, does not work. Also `log.exception` has `exc_info=True`, it basically is `log.error` with `exc_info=True`

**Comment by kosack** [comment]
I think the traceback output is handled by the logging Formatter - perhaps the custom formatter we use is missing this.

**Comment by kosack** [comment]
maybe it just need to be added to the default format string for the logger.  I notice that LogRecords contain an sinfo dict, but that is not in our log format:

https://docs.python.org/3/library/logging.html#logrecord-objects

**Comment by maxnoe** [comment]
The formatter implemented a custom formatting instead of using the one of the base class and just adding the color information.
