### ISSUE TITLE
indexing bug in DL1EventSource 

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1545]
The code here

https://github.com/cta-observatory/ctapipe/blob/a5ad0f181a2f1565324ce6af5c18a806c9b33dd5/ctapipe/io/dl1eventsource.py#L281-L283

adds 1 to the tel index to get the tel_id, but this is not correct in general, particularly if the subarray is a sub-selection of a larger array.   E.g. if we subselect only telescopes `[5,7,9,100]`, the tel_id to index map would be `[5: 0, 1: 7, 2: 9, 3:100]`, which is *not* `tel_index+1`

Therefore this should be changed to use the functions provided by `SubarrayDescription` to take care of this mapping, namely `sub.tel_ids_to_indices(tel_ids)` or `sub.tel_ids_to_mask(tel_ids)`

Example:
```py3
>>> sub = source.subarray.select_subarray("NewSubarray", [1,5,7,10])
>>> sub.tel_ids_to_mask([1,5,7])

array([ True,  True,  True, False])

>>> sub.tel_ids_to_indices([1,5,7,10])

array([0, 1, 2, 3])
```

There is no guarantee that `tel_id - 1 == tel_index`.

**Comment by maxnoe** [comment]
Indeed. Also this really should be a method in `SubarrayDescription`

**Comment by kosack** [comment]
One problem is that `tels_with_trigger` seems not to honor the subarray selected in EventSource, so perhaps fixing it there would help as well (or is it useful know if telescopes outside the subarray triggered, so not sure)
