### ISSUE TITLE
Pattern mismatch

### ISSUE THREAD

**Issue by Writasree** [cta-observatory/ctapipe#1565]
I'm extracting images using ctapipe from the muonic shower, simulated in CORSIKA at an energy of 1e5 GeV. The coordinates of the four telescopes given in CORSIKA are as follows-
 x(cm)   y(cm)   z(cm)          
 0       -8485     0            TEL. 1
 8485     0        0            TEL. 2
 0        8485     0            TEL. 3
-8485     0        0            TEL. 4
I'm attaching the telescopic images that I've got. I've arranged the telescopic images in accordance with the aforementioned geometric location.

![Muon_theta0_gamma1000](https://user-images.githubusercontent.com/29223716/101370533-9ee31500-38cf-11eb-8ca1-ca10235598b5.jpg)

While I was going through the slides presented by F. Montanet in ESIPAP 2014, I saw the telescopic images (labelled as 1,2,3,4 in green color font) given in slide no 92 ( the screenshot is attached below).

![Montanet_ESIPAP2014](https://user-images.githubusercontent.com/29223716/101370571-a86c7d00-38cf-11eb-85cb-4728984a0501.jpg)

 Even though the parameters in the input card may differ, the pattern of the image should have matched. I've expected diametrically opposite triggerings for oppositely located telescopes (as I can see in the screenshot). Why does the image obtained via ctapipe doesn't hold the pattern? Am I misunderstanding something or is there any internal rotation happening?

I'm using the following function to extract images-

```
def` display_event(event, source):
      ntels = `len(event.r0.tels_with_data)
      for ii, tel_id in enumerate(event.r0.tels_with_data):
                                nn = int(ceil(sqrt(ntels)))
                                ax = plt.subplot(nn, nn, ii + 1)
                                geom = source.subarray.tel[tel_id].camera.geometry
                                disp = CameraDisplay(geom, ax=ax)
                                disp.pixels.set_antialiaseds(False)
                                disp.autoupdate = False
                                disp.cmap = 'RdBu_r'
                                chan = 0
                                image = event.dl1.tel[tel_id].image
                                mask = tailcuts_clean(source.subarray.tel[tel_id].camera.geometry, image, picture_thresh=10, boundary_thresh=5)
                                cleaned = image.copy()
                                cleaned[~mask] = 0
                                disp.image = cleaned
                                

```
`
`

**Comment by kosack** [comment]
It seems your simulations are made with azimuth=180 degrees, which means you also have to rotate your cameras by 180 degrees. Also if the zenith angle is larger than 0, you would have to modify the telescope positions such that they are projected onto a plane normal to the pointing direction.

**Comment by maxnoe** [comment]
Please see #1564, where there is an example on how to do this.
