### ISSUE TITLE
No compatible EventSource for merged dl1 data products

### ISSUE THREAD

**Issue by Hckjs** [cta-observatory/ctapipe#1578]
meta description is `"Merged DL1 Data Product"` instead of `"DL1 Data Product"`.

**Comment by kosack** [comment]
The DESCRIPTION field is meant to be human readable, and shouldn't be relied on to identify the file type.  That should be done checking the other fields like:
* `CTA PRODUCT DATA LEVEL` == "DL1" 
* `CTA PRODUCT DATA MODEL NAME` == "ASWG DL1" 
* `CTA PRODUCT DATA MODEL VERSION` == a compatible version

**Comment by Hckjs** [comment]
So checking for
```
if "CTA PRODUCT DATA LEVEL" not in metadata._v_attrnames:
                return False
if metadata["CTA PRODUCT DATA LEVEL"] != "DL1":
                return False
```
in `DL1EventSource.is_compatible()` would be better than
```
if "CTA PRODUCT DESCRIPTION" not in metadata._v_attrnames:
                return False
if metadata["CTA PRODUCT DESCRIPTION"] != "DL1 Data Product":
                return False
```
?

**Comment by kosack** [comment]
Yes, those fields have a list of allowed values, whereas the description does not
