### ISSUE TITLE
stage1 does not write top level file properties when '--max-events' is used

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1584]
This means the DL1EventSource will not recognize the file as compatible.

**Comment by kosack** [comment]
I cannot reproduce this.  When i use --max-events as in the following: 
```
ctapipe-stage1 --config stage1_config.json --input ~/Data/CTA/Prod3b/LaPalmaBaselineNSBscan/gamma_20deg_180deg_run101___cta-prod3-demo-2147m-LaPalma-baseline.simtel.gz --output gammas5.dl1.h5 --progress --max-events=500 --log-level=INFO --overwrite
```
I get the user attributes:
![image](https://user-images.githubusercontent.com/11677812/106297473-0889fa80-6253-11eb-8b9b-84c7ccfface4.png)

**Comment by maxnoe** [comment]
Yes, seems to be something different that went wrong, sorry.
