### ISSUE TITLE
RawData dl1  item does not excecute RawData.__init__ method

### ISSUE THREAD

**Issue by jacquemier** [cta-observatory/ctapipe#160]
ctapipe/calib/camera/calibrators.py

This line:
calibrated.add_item("dl1", RawData)

Must be replace by:
calibrated.add_item("dl1", RawData())

**Comment by thomasgas** [comment]
@jacquemier This can be closed, right? just to clean a bit the issues :)

**Comment by dneise** [comment]
I say yes
