### ISSUE TITLE
Signal Shaping for Flash Cam

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1616]
As noted at some points already, FlashCam  needs a special treatment in the extraction, which is currently not implemented.

We would need input from the FlashCam teams on what exactly needs to be done and how it can be implemented.

**Comment by watsonjj** [comment]
Duplicate of #514?

**Comment by maxnoe** [comment]
Yes, my search skills were not good enough. I knew there was one. I search for signal shaping
