### ISSUE TITLE
DL1 Pointing tables are missing units

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1617]
I would expect array_altitude or array_azimuth to have units attached when I read them with `read_table`, but they do not seem to. Other tables read the same way do have the expected units attached.  This is with a *merged* DL1 file, so it could be some metadata getting lost

![image](https://user-images.githubusercontent.com/11677812/108392444-0512df00-7213-11eb-9fe2-9010bb5c5590.png)

**Comment by LukasNickel** [comment]
Adressed in #1614
