### ISSUE TITLE
`allowed_tels` should yield the corresponding subarray

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1623]
Currently, with allowed_tels set, event sources yield the full subarray.

This leads to an issue with merging and the dl1 event source, where setting allowed_tels for the merge tool results in a full subarray but missing image tables for the `DL1EventSource`.

**Comment by kosack** [comment]
Yes, this sounds reasonable - should just call ` subarray = subarray.select_subarray(name, allowed_tels)` then.

**Comment by maxnoe** [comment]
Fixed in #1736 and #1697
