### ISSUE TITLE
NoSuchNodeError in dl1_merge when first file doesn't contain image_statistics

### ISSUE THREAD

**Issue by Hckjs** [cta-observatory/ctapipe#1626]
Seen [here](https://forge.in2p3.fr/issues/41659#note-13). Should write an exception.

**Comment by kosack** [comment]
Do we know why the files doesn't have the image statistics dataset? It might mean the process crashed before finishing, which means the data might be corrupt or incomplete.  Should check the provenance file.

**Comment by maxnoe** [comment]
Yes, according to johan there was a zstd decompression error, so some kind of brocken input
