### ISSUE TITLE
Long/short cli options with traitlets should use tuples

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1631]
Using

```
aliases = {
    "s": "Foo.short"
    "short": "Foo.short",
}
```
Prints the option twice in the help.

Using 

```
aliases = {
    ("s", "short"): "Foo.short"
}
```

lists it only once.

**Comment by kosack** [comment]
Now fixed in Tool, and in stage1, but Still needs to be fixed in other tools (ctapipe-reconstruct-muons, etc).

**Comment by maxnoe** [comment]
REconstruct muons was removed recently, a quick look didn't find any more occurences, closing for now
