### ISSUE TITLE
Test that test multiple cameras no longer function

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1641]
We have a few tests that loop over all known camera types (testing many different camera geometries), for example test_geometry_converter.  These no longer seem to run on all cameras, since the datasets were moved to the server from ctapipe-extra.  The reason is that `CameraDescription.get_known_camera_names()` no longer returns all camera types, but only those that have been downloaded and cached recently.  This seems to have been broken by #1498

I suspect those tests do not even run if no camera geometries have been downloaded. 

We should fix this so that the old behavior works, even if it has to be hard-coded.  Ideally, it should be possible to fetch all known camera geometries on the dataset server.

**Comment by maxnoe** [comment]
> I suspect those tests do not even run if no camera geometries have been downloaded.

This is why I added the fixture for several camera geometries
