### ISSUE TITLE
Make ctapipe work with h5py version 3.0

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1642]
Right now we restrict to h5py < 3.0 because of how that version changed string writing broke astropy.

We should switch to allowing > 3.0 when astropy supports it.

**Comment by kosack** [comment]
Ideally, there would be a  pytables backend for astropy, and we could drop h5py as a dependency. 

We also had mentioned replacing using `astropy.Table.write()` to write the instrument description to HDF5 files and rolling our own solution (which is a bit annoying to have to do, but gives complete control). I would guess in the end that solution could be contributed back to astropy, though.

**Comment by maxnoe** [comment]
I discussed this with the astropy maintainers and they were reluctant on adding this kind of non-standardized extension based on hdf5 attributes. 

But using this yaml extension is not really portable...

**Comment by maxnoe** [comment]
Relevant PR in astropy, schould be backported to 4.0.5, 4.2.1:
https://github.com/astropy/astropy/pull/11359
