### ISSUE TITLE
HDF5TableWriter cannot append to existing table

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1655]
Even when opening with using `mode='a'`, the writer cannot actually append to an already existing table.

**Comment by kosack** [comment]
I think append only allows one to append new datasets, not to existing tables. What is the use case of this?

**Comment by kosack** [comment]
It would have to avoid creating the group and table in append mode.  This was not a use case I supported, to keep the code as simple as possible, but it shouldn't be hard to do if really needed.  I don't quite see why you couldn't just merge existing files, though

**Comment by maxnoe** [comment]
It is not a stage1 output. I just made a custom tool to extract some lst counters from multiple files and wanted to append to the same output file.
