### ISSUE TITLE
undefined function in __all__ in io/astropy_helpers

### ISSUE THREAD

**Issue by nbiederbeck** [cta-observatory/ctapipe#1733]
https://github.com/cta-observatory/ctapipe/blob/3cd627a0af7156a53f331bab2b18408976929dd7/ctapipe/io/astropy_helpers.py#L21

I assume it should be `read_table`?
https://github.com/cta-observatory/ctapipe/blob/3cd627a0af7156a53f331bab2b18408976929dd7/ctapipe/io/astropy_helpers.py#L24

**Comment by maxnoe** [comment]
yes, this is an oversight when the function got renamed.

**Comment by nbiederbeck** [comment]
Any way to catch this in automated tests?

**Comment by nbiederbeck** [comment]
Yes, with flake8:
```
$ flake8 ctapipe/io/astropy_helpers.py
ctapipe/io/astropy_helpers.py:21:1: F822 undefined name 'h5_table_to_astropy' in __all__
```
