### ISSUE TITLE
Stage1 tool's `--write-parameters` flag is superflous 

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1738]
The stage1 tool has a flag `-write-paramters` that's not useful since it can only set `DataWriter.write_parameters` to True, which already is the default.

Flags are only useful if they set values other than the default.

There is also currently no nice way to deactivate writing parameters, so the flag should probably be `--no-parameters` instead.

We could also follow a common pattern and provide pairs of flags for everything, so I would propose to change

`--write-images`, `--write-paramters` to `--images`, `--no-images`, `--parameters`, `--no-parameters`.

**Comment by kosack** [comment]
I'm actually surprised that traitlets.config's "boolean flag" functionality doesn't automatically add negative flags... it really should (e.g. `--no-write-images`).  Or we make the defaults all False maybe?

**Comment by kosack** [comment]
In any case, we may have to think about what these really mean in the future: I called them `write-X` for a reason: they do not tell the tool if it should *compute* them (that depends on  the input), only if they should be in the output.

**Comment by nbiederbeck** [comment]
> I'm actually surprised that traitlets.config's "boolean flag" functionality doesn't automatically add negative flags... it really should (e.g. `--no-write-images`). Or we make the defaults all False maybe?

Actually it does, when using `traitlets.config.boolean_flag` (or `ctapipe.core.traits.flag` as we call it):
```
flag("write-parameters", "DataWriter.write_parameters", "store parameters in output", "dont store"))
```
yields the following `--help` output:
```
--write-parameters
    store parameters in output
    Equivalent to: [--DataWriter.write_parameters=True]
--no-write-parameters
    dont store
    Equivalent to: [--DataWriter.write_parameters=False]
```

**Comment by maxnoe** [comment]
Ha, nice. Can you make a PR fixing that for our tools?

**Comment by nbiederbeck** [comment]
Will do
