### ISSUE TITLE
Completely remove 2d geometries

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1743]
I think it will make things much more consistent, if we stick with 1d geometries, as all the normal geometries are this way and it will make implementing more geometry features easier if we only have one dimensioniality to worry about.

To keep the geometry conversion functionality, I would propose to make sure that this results in a row major array, so deep learning and other algorithms requiring classical images can just do

``` 
image.reshape(converted_geometry.shape2d)
```

or 
```
image2d = geometry.to_2d_image(image)
```

**Comment by kosack** [comment]
sounds ok, then the GeometryConverter that makes "skewed" geometries now would just return a new 1D array with he shape. I think that is ok.

**Comment by maxnoe** [comment]
Done in #1728
