### ISSUE TITLE
Relative path to config file in tests

### ISSUE THREAD

**Issue by nbiederbeck** [cta-observatory/ctapipe#1750]
The tool tests have the following line:
```python
config = Path("./examples/stage1_config.json").absolute()
```

This failed me on `pytest` *inside* of `ctapipe/tools` instead of `pytest ctapipe/tools`. 

Fix needed or should I just run local test the correct (second) way?

**Comment by maxnoe** [comment]
No, please fix. This also prevents running the tests in the installed package using `pytest --pyargs ctapipe`, so we should fix that.

**Comment by maxnoe** [comment]
We need to make sure the files are bundled in the package and we should use `importlib_resources` to use them.

**Comment by kosack** [comment]
we could also put the config files on the dataserver instead
