### ISSUE TITLE
Make it possible to use urls for config files

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1754]
Currently, and especially once #1726 is merged, the overall functioning of `ctapipe-stage1` and later `ctapipe-process` is driven by configuration files that are increasingly complex.   To support reproducible analysis, it is clear we need a repository for configurations used for CTA studies in the CTA-GitLab.  It would be nice for ctapipe to support accessing configurations from such a repo directly, without the need to check out the repo and switch to the requested version.  

I suggest we add a URL scheme (using what is already possible in `get_dataset_path()`) and support using urls in the `--config` option of Tools.  Not sure if we need a specific `git://` or `config://` URL scheme, or if we can just use the GitLab/GitHub API urls to access the files via `https://`. 

## Requirements:
* should be able to specify the repo location (not tied to CTA's repo specifically)
* should be able to specify which config file to use 
* should be able to specify the version tag or hash

**Comment by maxnoe** [comment]
This should now be as simple as using the `Path` trait for the config file
