### ISSUE TITLE
Unit tests for download functionality don't run due to the cache

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1762]
Now that we cache the unit test files, the code that fetches those files from the dataserver is never run, and thus all current PRs have a (false) positive increase in the project-level code coverage, leading them to all be marked as *failed*.

Is there a way we can fix that? Perhaps running a single unit test that downloads a file without caching, or removing that file from the cache later?

**Comment by maxnoe** [comment]
We just need to add proper tests for the download functions, right?
