### ISSUE TITLE
Use new github features

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#178]
I think it would be a good idea to use the new github features for enhanced review:

* protect the master branch
* require at least one or two approved reviews for a pull request

**Comment by kosack** [comment]
Sounds great to me. I wasn't aware those were even available. Of course, we always have in mind that we will at some point migrate to a locally-hosted GitLab instance, but I guess those same features exist there as well (or will soon).

**Comment by kosack** [comment]
Done. I protected the master branch and require a review for merges. The only option I saw was for 1 review not 2, but that is sufficient for now.
