### ISSUE TITLE
Unit tests fail because my name has non ascii characters

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1788]
The unit tests currently fail on my system (`ctapipe.tools.tests.test_tools::test_ctapipefileinfo`) because I have an umlaut in my name and writing the file info to FITS fails with an could not encode to ascii error.

Seriously....?

**Comment by maxnoe** [comment]
Somehow it gets my name magically from the system.

The error was not even printed.

This took me an hour to find out that MY NAME is the problem

**Comment by maxnoe** [comment]
And fileinfo depends on pandas although we removed pandas from our dependencies...

**Comment by kosack** [comment]
It's always good to work with non-English names when unicode/ascii is involved :-) 

See also: https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/
