### ISSUE TITLE
Fix failing test

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#180]
There is one test, which fails on travis: `ctapipe/utils/tests/test_json_2_fits.py::test_traitlets_config_to_fits`

This test is successful on my machine. Any Idea why it fails on travis?

**Comment by jacquemier** [comment]
This test uses astropy.io fits module.
Please try to update your astropy module.

**Comment by MaxNoe** [comment]
My version is newer than what is used on travis ;)

**Comment by jacquemier** [comment]
I have no doubt with that ;-)
Sorry., my answer is in wrong repo.

By the way I will try to update astropy version for travis.
