### ISSUE TITLE
CameraDisplay's pixel picker broken

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1832]
**Describe the bug**
Clicking on a pixel displays the highlighted pixel in the wrong position for CHEC camera, and clicking pixels stops working if the CameraDisplay is zoomed.

**To Reproduce**
```py3
geom = subarray.tel[35].camera.geometry  # a CHEC camera
disp = CameraDisplay(geom)
disp.enable_pixel_picker()
```
then click a pixel

**Expected behavior**
Pixel should be highlighted, and a message "clicked pixel XX" written to the console by default (user overridable to do something useful). 
Additionally, the clicking of pixels should still work when one zooms in on the CameraDisplay, as it used to work.

**Supporting information**
Broken completely for CHEC: (highlighted pixel appears in wrong position)
![image](https://user-images.githubusercontent.com/11677812/151408404-fbb4c8bd-1a60-4447-aff6-fc665337a364.png)

Highlighting works for LSTCam, but can no longer click after zooming:
![image](https://user-images.githubusercontent.com/11677812/151408684-f545bd06-5599-4cb1-b3b4-64dca239b82b.png)

**Additional context**
This feature is used in interactive displays used in test benches

**Comment by maxnoe** [comment]
The first issue comes from merging #1819 which switched the patch from a `Rectangle` to a `RegularPolygon` for square pixels, making the subtraction of the pixel_width wrong.

**Comment by maxnoe** [comment]
Fix here: https://github.com/cta-observatory/ctapipe/pull/1833

**Comment by maxnoe** [comment]
I cannot reproduce the problem with zooming though.

Note: you have to deselect the zoom tool / magnifying glass to be able to click on pixels again.
