### ISSUE TITLE
Configuration module uses status codes

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#188]
The configuration modules return status codes. 

They should raise exceptions instead.

**Comment by jacquemier** [comment]
Which configuration module ?
ctapipe.util.json2fits ?

**Comment by MaxNoe** [comment]
Yes.

**Comment by MaxNoe** [comment]
They do stuff like

```{python}
try:
    stuff()
except IOError:
    return False
return True
```

I do not think this is a good idea. Also for logging exceptions, there is `logging.exception` which includes the traceback.

```{python}
try:
    stuff()
except:
    logging.exception('Could not do stuff')
    raise
```
Would log the exception including traceback and the raise the same exception. So only logging is added.

**Comment by jacquemier** [comment]
https://github.com/cta-observatory/ctapipe/pull/196
