### ISSUE TITLE
DL2 quality query statistics are called "image_statistics" and are not merged by merge tool

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1884]
**Describe the bug**

The statistics of the reconstructor quality query are stored in `/dl2/service/image_statistics` and are not handled by the merge tool.

This has some problems:

* It should not be called image statistics
* It should have the reconstructor name in it
* merge tool should handle it

**Comment by kosack** [comment]
They were called `dl2/image_statistics` because they were statics on how many telescope images passed, not on how many showers were reconstructed
