### ISSUE TITLE
Store telescope impact distance in simulation container

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1892]
sure, it can be computed from those values, but the calculations are not trivial and require also digging out the telescope positions from the array description (and making sure that everything is in the same reference frame) 
since it is really useful, and  it is just one number per telescope I think it is really worth to keep it stored

_Originally posted by @jsitarek in https://github.com/cta-observatory/ctapipe/issues/1891#issuecomment-1106439147_

**Comment by maxnoe** [comment]
In what frame do we want this information? I guess it's more useful in the tilted frame?

**Comment by jsitarek** [comment]
impact is defined as the distance of the telescope from the shower axis (in a sense of a mathematical distance of a point from a line, so measured in the perpendicular plane), so yes, it is easiest to compute it in the tilted frame

**Comment by maxnoe** [comment]
> (in a sense of a mathematical distance of a point from a line, so measured in the perpendicular plane)

That is probably the easier way to calculate it, instead of going through the coordinate transformations. Will habe a look.

**Comment by kosack** [comment]
We currently compute it in the TiltedFrame aligned with the pointing direction.  I think really it should be in a ShowerFrame (how a person riding on each shower sees the array), but the difference is probably within reconstruction error for sources in the FOV (assuming small angle between the point of origin and the center of the field of view).

**Comment by kosack** [comment]
I should mention in protopipe we do compute and store this right now, and it is quite useful to do so to avoid a complicated computation later which is not so easy to add as a simple "feature" in the machine learning steps.  So I would agree to add it to both the SimulationContainer and ideally somewhere in the reconstructed DL2/telescope/geometry data as well.

**Comment by moralejo** [comment]
> We currently compute it in the TiltedFrame aligned with the pointing direction. I think really it should be in a ShowerFrame (how a person riding on each shower sees the array), but the difference is probably within reconstruction error for sources in the FOV (assuming small angle between the point of origin and the center of the field of view).

Definitely it has to be relative to shower axis, and I think the difference could be pretty large even within FoV, because of distance to shower is way larger than the radius of the light pool.

**Comment by kosack** [comment]
Yes, I think you are right that we should do it properly.  This implies we should just make a `Component` to compute it that runs after all Reconstructors.

**Comment by kosack** [comment]
something like:
```py3
   impact[tel_id] = np.cross(sky-ground, sky-tel[tel_id])/np.linalg.norm(sky-ground)
```
where sky, ground, and tel are all 3d points

**Comment by kosack** [comment]
I made a PR above.  There is still a bug since I did it two ways and they don't agree at certain azimuth angles, so if anyone sees the error, let me know (could also be a bug in the TiltedFrame transforms).

However, assuming it will work correctly, the question now is where to put the pre-computed telescope-wise impact parameters? They could go:

1. in their own table:  */dl2/event/telescope/impact*   and  */simulation/event/telescope/impact *
2. in /*dl2/event/subarray/geometry* as a vector column (not so easy to use it in machine learning then, however)
3. somewhere else?

Any ideas?

**Comment by maxnoe** [comment]
Like I said here, at least for the true impact and true image sum I would add a telescope table group at `/simulation/event/telescope/<???>` 

I didn't yet come up with a good name, since parameters already refers to the image parameters as calculated on the true image.

**Comment by kosack** [comment]
Agreed that makes the most sense. It's a parameter that requires either a reconstruction or a simulated shower, so we could put it in it's own table like `/{simulation,dl2}/event/telescope/impact/tel_XXX`:

```py3
class ImpactParameterContainer(Container):
    impact_distance =  Field(...)
    impact_distance_uncert = Field(...)
```
