### ISSUE TITLE
ctapipe.io.hessio class  issue

### ISSUE THREAD

**Issue by jacquemier** [cta-observatory/ctapipe#19]
Dear Karl,

I think there is a bug in the ctapipe.io.hessio class
Only one Container instance is create before the loop on the event.
Then inside the loop, it always uses the same instance.
So we cannot keep an instance of this container in a list for example:
See example bellow

For information, copy a Container class does not work.

============================ Test code =====================
from ctapipe.io.hessio import hessio_event_source
from ctapipe.configuration.core import Configuration, ConfigurationException
from ctapipe.core import Container
from ctapipe.utils.datasets import get_path

if __name__ == '__main__':
    raw_data = '/home/jacquem/workspace/data/gamma_20deg_0deg_run31964___cta-prod2_desert-1640m-Aar.simtel.gz'
    source = hessio_event_source(get_path(raw_data), max_events=10)
    
    l = list()
    for event in source:
        print (event.dl0.event_id)
        l.append(event)
        
    print( "+---- list ----+") 
    for event in l:
        print (event.dl0.event_id)

__________________RESULT____________________
jacquem>python test_hessio.py 
/home/jacquem/workspace/data/gamma_20deg_0deg_run31964___cta-prod2_desert-1640m-Aar.simtel.gz

Input file '/home/jacquem/workspace/data/gamma_20deg_0deg_run31964___cta-prod2_desert-1640m-Aar.simtel.gz' has been opened.

Starting run 31964
408
409
803
4907
9508
10104
10109
11905
12202
12203
17301
+---- list ----+
17301
17301
17301
17301
17301
17301
17301
17301
17301
17301
17301

**Comment by kosack** [comment]
That's by design, actually. If more than one instance is used, the memory usage can be very large, so it just keeps one in memory at a time.  To make a list that keeps each entry,  you can just change your code to be:
```python
for event in source:
    l.append(copy(event))
```
The problem was that in your example, you were making a list of references (all to the same object).
