### ISSUE TITLE
HDF5EventSource only supports image parameters in telescope frame for current files

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1922]
**Describe the bug**

The HDF5EventSource checks the data model version to decide whether to read a `HillasParametersContainer` or a `CameraHillasParametersContainer`. This does not support the `--camera-frame` switch of the current `ctapipe-process`.

We should either:
a) Handle current files with hillas parameters in camera frame
b) just drop support for hillas parameters in camera frame everywhere

**Comment by kosack** [comment]
We could also just drop the `--camera-frame` option, as it is no longer needed - it was there to be able to test the implementation in the TelescopeFrame, but as that works, we could remove a lot of code

**Comment by maxnoe** [comment]
This was fixed in  #2079
