### ISSUE TITLE
rename ML reconstruction classes

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1955]
## Problem
Right now the hierarchy in the `ml`  module is:

```
Reconstructor
     - RegressionReconstructor
         - EnergyRegressor
     - ClassificationReconstructor
         -  ParticleIDClassifier
```

This has two problems:
1. This may cause problems as we also have a `Reconstructor` base class in the `reco` module (and traitlets uses class names to set parameters). 
2. It is better to have the base class in the name of the sub-class, so it's clear to a reader that it is a subclass (when possible)

## Suggested solution:

rename `ml.Reconstructor` → `ml.Predictor`?  (could also see if there is a better word..)

Then you have something like:

```
Predictor
    - RegressionPredictor
        - EnergyRegressionPredictor
    - ClassificationPredictor
        - ParticleClassificationPredictor 
```

**Comment by maxnoe** [comment]
Sounds good to me

**Comment by maxnoe** [comment]
The class hierarchy was changed before #1767 was merged
