### ISSUE TITLE
Remove support for reading older file versions

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1983]
**Please describe the use case that requires this feature.**
With the planned and already merged changes to the data model (#1923, #1949, #1899, #1426, #1591  and some others) I think we are at the point where we should remove a number of  workarounds and compatibility layers to simplify the code.

**Describe the solution you'd like**

Drop support for all but the current version of the data model to simplify the code.

**Describe alternatives you've considered**

Keep maintaining these workarounds and compatibility layers. I don't think we should do this, especially not for 1.0.

**Comment by kosack** [comment]
Yes, I think this is ok . we are still in a pre 1.0 release, so shouldn't worry too much about backward compatibility
