### ISSUE TITLE
Design pattern for Visualization modules

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#2]
Right now, the CameraDisplay is a generic class that uses a backend renderer (from a class hierarchy).  Is there a nicer way to support multiple backends?

**Comment by kosack** [comment]
For now, I'm just not making it as flexible. I just have a basic version using MatPlotLib, and we can refactor later to support others

**Comment by cdeil** [comment]
I have a Python book on my desk ... it recommends (I think) a Pythonic abstract factory pattern for something like this. I haven't looked at what you implemented yet and if it makes sense. Come by my office if you want to have a look ...
