### ISSUE TITLE
Treat disabled pixels

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2017]
**Describe the bug**

Prod6 FlashCam MSTs contain 6 disabled pixels, three inside the main camera, three at the edges:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/5488440/179201716-4dbfe60d-a5a6-446d-ae89-addfcb3419e7.png">

(Image provided by @orelgueta)

we currenly don't deal at all with disabled / broken pixels and the NeighborPeakWindowSum creates very strange results:

![strange_flashcam](https://user-images.githubusercontent.com/5488440/179201979-d255ee17-069d-4ca3-bc47-54605b4604a6.png)

**To Reproduce**

Run a prod6_run Paranal

**Expected behavior**
Ignore / Interpolate disabled pixels

**Comment by orelgueta** [comment]
For the record, these disabled pixels were there also in Prod5.
