### ISSUE TITLE
Improve performance of HillasReconstructor

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2025]
**Please describe the use case that requires this feature.**

HillasReconstructor is dominating the runtime of processing simtel files up to DL2 training. A cursory glance at the code lets me think there is a lot of room for easy improvement. 

**Describe the solution you'd like**

Refactor `HillasReconstructor` code to optimize performance.

**Comment by kosack** [comment]
most of the time is taken in the coordinate transforms and creating coordinates. It's likely that could be optimized

**Comment by maxnoe** [comment]
Most of this was done in #2036
