### ISSUE TITLE
Merging of simulated impact distance / merging of telescope DL2

### ISSUE THREAD

**Issue by nbiederbeck** [cta-observatory/ctapipe#2048]
Not sure whether this is a Bug or a Feature Request or both

1) We currently don't merge the simulated telescope impact parameters `/simulation/event/telescope/impact`. I think this is a quick fix.

2) We don't merge anything other DL2 than `dl2/event/subarray/geometry`. This includes (not merging) e.g. `HillasReconstructor_tel_distance`, which gets calculated in the most basic DL2 "pipeline" of only Hillas Reco.

**Comment by kosack** [comment]
This is probably not a feature but a bug! (or a missing feature rather!)

**Comment by kosack** [comment]
Ah, that is also a bug... The Container has a prefix of "impact" so the intention was that the column name is: `impact_distance` not `tel_distance`.   Not sure why that changed?

**Comment by nbiederbeck** [comment]
I added a PR that will fix this (in addition to #2049) and created a new issue for the naming bug.
