### ISSUE TITLE
Hillas calculation failed for some telescopes in camera-frame

### ISSUE THREAD

**Issue by TjarkMiener** [cta-observatory/ctapipe#2062]
**Describe the bug**
I'm using the latest ctapipe version (v0.16.0) with a subsample of Prod5b. When running the process tool, the Hillas calculation failed (either zeros or nan) for some telescopes in camera-frame.

**To Reproduce**
1. `$ ctapipe-process -i /data3/users/nieto/Prod5b_sample/Prod5b_LaPalma_AdvancedBaseline_NSB1x_gamma_North_20deg_DL0_1e6evt/gamma_20deg_0deg_run126___cta-prod5b-lapalma_desert-2158m-LaPalma-dark.simtel.zst --progress --write-images --write-parameters --write-showers --camera-frame`

**Expected behavior**
Hillas calculation should be also working when camera-frame is selected.

**Supporting information**
Screenshot with corrupted tables for tel 3 (LST) and tel 6 (MST with NectarCam):
![Screenshot from 2022-09-05 11-56-20](https://user-images.githubusercontent.com/37835610/188423940-215e395d-6352-4c05-8836-9d13633a60fb.png)
Provenance log:
[ctapipe-process.provenance.log](https://github.com/cta-observatory/ctapipe/files/9488873/ctapipe-process.provenance.log)

**Additional context**
It would be also great to store the information about the camera-frame in the meta data and just keep one naming convention for the parameter tables, i.e. removing the prefix "camera_frame_"

**Comment by maxnoe** [comment]
I suspect the problem is that for these telescopes the first event is not reconstructible, we then provide the wrong default container and that messes up all following events.


Let me check

**Comment by maxnoe** [comment]
Yes, this is the case. We return the global `DEFAULT_IMAGE_PARAMETERS`, which always contains the `telescope_frame` variant. 

I'd solve this by just going ahead and removing the `--camera-frame` option to be honest and not add further complication for something we do not intend to support anymore.

**Comment by maxnoe** [comment]
On the other hand, the fix wasn't too hard...
