### ISSUE TITLE
Stable optics and camera indices 

### ISSUE THREAD

**Issue by TjarkMiener** [cta-observatory/ctapipe#2063]
**Please describe the use case that requires this feature.**
Minor stylistic request to improve consistency between runs of one production. 

**Describe the solution you'd like**
Define an order (i.e. linked to tel ids)

**Additional context**
<img width="1125" alt="Screenshot 2022-08-26 at 15 02 10" src="https://user-images.githubusercontent.com/37835610/188427499-89efb062-8691-4ad5-8b3a-5914d67bd786.png">

**Comment by maxnoe** [comment]
> ? I thought in python 3.6+ dicts and sets were ordered, but I may be wrong about sets.

Only dicts

**Comment by kosack** [comment]
I still don't quite see why files with the exact same subarray in them would end up with these keys in a different order - are we sure the example files at the top of this issue have the same subarray description? If not, then the order would not be expected to be the same. 

As @maxnoe  said, nobody should rely on it being the same either, as it is an internal mapping to build the SubarrayDescription, not something the user should even care about.

**Comment by maxnoe** [comment]
@kosack if you want to know the CPython implementation detail that causes this, it is two things:

1. set iteration order happens to be ordered by hash
2. string hashes are randomized between python interpreter sessions:
```
❯ python -c 'print(hash("Hello, World!"))'
7918248467824148683
❯ python -c 'print(hash("Hello, World!"))'
-2028356294309276154
❯ python -c 'print(hash("Hello, World!"))'
2766964094343225856
```

**Comment by kosack** [comment]
Then I think it is a good idea to sort first - having the output change slightly between runs with the same input is certainly unexpected.
