### ISSUE TITLE
True MC times

### ISSUE THREAD

**Issue by clara-escanuela** [cta-observatory/ctapipe#2074]
The true MC time when photons are converted into photoelectrons cannot be read with ctapipe. At the moment, they can only be accessed via pyeventio. It would be nice to be able to extract that information directly with ctapipe to have direct and clear information of the true and reconstructed parameters.

**Comment by maxnoe** [comment]
Hi,

This seems to be the same issue as: https://github.com/cta-observatory/ctapipe/issues/1682

I will close this issue as a duplicate (sorry I didn't check before when answering your email) and will provide more details there.
