### ISSUE TITLE
Python 3.11 support 

### ISSUE THREAD

**Issue by LukasNickel** [cta-observatory/ctapipe#2103]
Python 3.11 is out now, we should add it to the CI
(https://www.python.org/downloads/release/python-3110/)

Not a whole lot changed, should be smooth sailing.
Do we remove 3.8 now?

**Comment by maxnoe** [comment]
We decided to follow the  nep29 schedule, which means dropping 3.8 in April 2023

**Comment by kosack** [comment]
It also usually takes a little while for there to be conda packages built for a new python release, but we could open a PR now and use that to monitor when the tests pass.

**Comment by maxnoe** [comment]
conda-forge packages for 3.11 are already available

**Comment by maxnoe** [comment]
But I guess it will take a while for numpy and co

**Comment by maxnoe** [comment]
The main blocker is numba, tracking issue here: https://github.com/numba/numba/issues/8304

**Comment by maxnoe** [comment]
This was done in #2107
