### ISSUE TITLE
ReconstructedGeometryContainer units do not match for HillasReconstructor

### ISSUE THREAD

**Issue by StFroese** [cta-observatory/ctapipe#2118]
**Describe the bug**
The ReconstructedGeometryContainer does return angles in rad instead of deg when using HillasReconstructor.

**To Reproduce**
```python
In [2]: from ctapipe.io import EventSource
   ...: from ctapipe.reco import HillasReconstructor
   ...: 
   ...: 
   ...: source = EventSource("/Users/stefan/Downloads/gamma_20deg_180deg_run3___cta-prod6-paranal-2147m-Paranal-dark.dl2.h5", max_events=1)
   ...: events = list(source)
   ...: 
   ...: reco = HillasReconstructor(source.subarray)
   ...: 
   ...: for event in events:
   ...:     reco(event)
   ...: 

In [3]: event.dl2.stereo.geometry['HillasReconstructor'].alt
Out[3]: <Latitude 1.21863615 rad>
```

**Expected behavior**
Should return angle in deg.

```
ctapipe.containers.ReconstructedGeometryContainer:
                           alt: reconstructed altitude with default nan deg
                                [deg]
```

**Solution**
Not sure but I guess the Container just has to be validated.

**Comment by StFroese** [comment]
Ok I just saw this comment in the Container validation code: `This is not intended to be run every time a Container is filled, since it is slow, only for testing a first event.`

So in this case maybe just convert the units upfront for HillasReco

**Comment by maxnoe** [comment]
The point of having unit information attached is that the units don't really matter as long as they are of the correct dimension.

So yes, it would be nicer to be consistent, but it's not a bug per-se and `Container.validate` checks `self.unit.is_equivalent(value.unit)`, not `self.unit == value.unit`:

```
In [1]: from ctapipe.containers import ReconstructedGeometryContainer

In [2]: import astropy.units as u

In [3]: ReconstructedGeometryContainer(alt=20 * u.deg).validate()

In [4]: ReconstructedGeometryContainer(alt=0.5 * u.rad).validate()

In [5]: ReconstructedGeometryContainer(alt=0.5 * u.m).validate()
...

UnitConversionError: 'm' (length) and 'deg' (angle) are not convertible
```

**Comment by maxnoe** [comment]
And in the output files, it is converted to the `Field.unit`.

**Comment by StFroese** [comment]
Ah ok I didn't check that
