### ISSUE TITLE
`ctapipe-apply-models` does not keep order of events

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2125]
**Describe the bug**

The tables written by `ctapipe-apply-models`, due to the use of astropy joins, are ordered by obs_id, event_id, not as in the input tables (e.g. `/dl1/event/subarray/trigger` or `/dl2/event/subarray/geometry/HillasReconstructor`

This prevents the optimization discussed here #2114 

**Expected behavior**
Keep order of events

**Comment by LukasNickel** [comment]
Is this what I did here basically?
https://github.com/fact-project/aict-tools/blob/ee091fc933110ff008e32df02ee12a97e412e8b3/aict_tools/io.py#L507

Cant check it in detail, but it reminded me on a Problem I had back then

**Comment by StFroese** [comment]
@maxnoe can this be closed with #2126 ?

**Comment by maxnoe** [comment]
Yes, fixed.
