### ISSUE TITLE
Add multiplicity explicitly to output containers

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2127]
**Please describe the use case that requires this feature.**

We put `telescopes` into the stereo output containers, so the information is there in principal, but I think it would be very convenient to also simply store the number of telescopes.

**Comment by StFroese** [comment]
So basically this?
```python
AStereoOutputContainer(
...,
telescopes=telescopes,
multiplicity=len(telescopes),
)
```

**Comment by maxnoe** [comment]
Yes, or `np.count_nonzero(telescopes)` if telescopes is already the mask, not the list of telescope ids.

**Comment by StFroese** [comment]
Ok, great. Since there will be no tel_id 0, this will catch both cases

**Comment by maxnoe** [comment]
In another discussion, we decided against this and instead implemented the `multiplicity` function on the `SubarrayDescription` to be used in e.g. quality queries
