### ISSUE TITLE
Allow dropping dl1 and telescope-wise information in `apply-models` or add tool for that.

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2130]
**Please describe the use case that requires this feature.**
Currently, `apply-models` just copies the input file, with everything inside it.

We should add options – or a second tool – to only copy subsets, e.g. the metadata + instrument + event/subarray data

**Comment by StFroese** [comment]
Ah ok. So something like `apply-model --reduced-data`

**Comment by nbiederbeck** [comment]
Maybe `ctapipe-merge` would also benefit from some sort of Copy Component
