### ISSUE TITLE
CI does not test macos with python 3.9

### ISSUE THREAD

**Issue by nbiederbeck** [cta-observatory/ctapipe#2154]
Did we just forget it, or is there a specific reason?

Also, our test matrix regarding conda/pip is really sparse:

| | ubuntu | macos |
| --- | --- | --- |
| 3.8 | conda | pip |
| 3.9 | conda | - |
| 3.10 | conda, pip, conda+codecov | conda |

**Comment by maxnoe** [comment]
At the time we chose a specific, sparse set of combinations to not have too many different CI jobs.
