### ISSUE TITLE
CameraGeometry.from_name

### ISSUE THREAD

**Issue by Nicoecap** [cta-observatory/ctapipe#2157]
I tried to plot one simulated SST gamma ray image from a one dimensional numpy array, that I extracted from .DL1.h5 files.

Code to reproduce the behavior:

```
from ctapipe.visualization import CameraDisplay
from ctapipe.instrument import CameraGeometry

geom = CameraGeometry.from_name("CHEC")
disp = CameraDisplay(geom)
disp.add_colorbar()
disp.image = gammas[2, :, 1]  #numpy array with shape: (2048,)
plt.savefig("path")
```

I expected to get plots that show showers that are not distorted/distributed (cf. plot) all over the image.

**Additional context**
```
python version : 3.9.7.final.0
ctapipe                   0.17.0
ctapipe-extra             0.3.1
```

The same happens when I try DL1.h5 data like: 

```
data.root.dl1.event.telescope.images.tel_030.col("image")[10]
```
instead of my numpy arrays.

My guess would be that the geometry does not match my data in some way.
![ctapipe-after-transformation](https://user-images.githubusercontent.com/95627436/206285799-8834e9a9-3632-4400-86c5-593bca39302f.png)

**Comment by maxnoe** [comment]
Hi @Nicoecap ,

`CameraGeometry.from_name` downloads a rather old simulation file from the data server and gives you that version of `CHEC`. You shouldn't rely on that function for any real analysis, instead, read the instrument information from your input file. ctapipe output files always contain the full subarray information.

You can access this in multiple ways, for example when using `TableLoader`:

```
with TableLoader("path/to/file.h5", load_images=True) as loader:
    # this loads all events for telescopes matching this description
    events = loader.read_telescope_events("SST_SST_CHEC")
    subarray = loader.subarray

tel_id = <some tel_id of an sst>
geometry = subarray.tel[tel_id].camera.geometry
```


Or directly using `Subarray.from_hdf()`:

```
subarray = Subarray.from_hdf("path/to/file.h5")
camera = subarray.tel[tel_id].camera.geometry
```

This is not a bug, simulation configurations and real data cameras change. You need to load the correct subarray information for the data you are working with. `CameraGeometry.from_name` should only be used for quick tests.

**Comment by Nicoecap** [comment]
Both TableLoader and Subarray.from_hdf raise the same error:
ctapipe/instrument/subarray.py", line 593, in from_hdf
    raise IOError(f"Unsupported version of subarray table: {version}")
OSError: Unsupported version of subarray table: 1.0

I am not quite sure if that is related to my original topic.

I am trying to load something like: proton_20deg_0deg_run4424___cta-prod5-paranal_desert-2147m-Paranal-dark_merged.DL1.h5

Thanks for the help!

**Comment by maxnoe** [comment]
> Both TableLoader and Subarray.from_hdf raise the same error:
ctapipe/instrument/subarray.py", line 593, in from_hdf
raise IOError(f"Unsupported version of subarray table: {version}")
OSError: Unsupported version of subarray table: 1.0

That means you are trying to load a dl1 file that was produced with an older version of ctapipe than the one you are using currently. We had to break backwards compatibility with older input files to enable e.g. storing both equivalent and effective focal length and more information in the `CameraReadout`.

You either
a) need to use the same version of ctapipe used to create the file or
b) recreate the file with the current version of ctapipe
