### ISSUE TITLE
ctapipe-merge does not treat metadata 

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2164]
**Describe the bug**
After merging, contact and site info are empty defaults. We should take them from the input files if no other information is provided via the config system.

**To Reproduce**

Merge files that do have contact info / subarray info defined and look at `ctapipe-fileinfo merged_file.h5`

**Comment by Tobychev** [comment]
@maxnoe did #2179 solve this issue?

**Comment by maxnoe** [comment]
Yes, indeed, thanks!
