### ISSUE TITLE
CTAPIPE_SVN_PATH vs cache directory

### ISSUE THREAD

**Issue by HealthyPear** [cta-observatory/ctapipe#2169]
Not sure if I got how this works now...

I am pretty sure I understood that we do not use ctapipe-extra since a long time, instead we download from a remote server.

When test files are downloaded they go to something like `$HOME/.cache/ctapipe` and that's fine.

Then functions like `find_all_matching_datasets` use this `CTAPIPE_SVN_PATH` quite explicitly, but I never set one as I do not really need it if the data for the tests goes into the cache.

Shouldn't this environment variable have as default value at least the cache directory?

**Comment by maxnoe** [comment]
First: It's `CTAPIPE_SVC_PATH` for service.

The logic of `get_dataset_path` is to check at several locations and return the first that finds the file.

The order is:

1. `CTAPIPE_SVC_PATH`, if it is set
2. if not, the file will be downloaded. The download function caches the results, by default in `$HOME/.cache/ctapipe`

Providing `CTAPIPE_SVC_PATH` is important, for example for things like cluster nodes without internet. You can then put all required data files into some directory and `export CTAPIPE_SVC_PATH`.
