### ISSUE TITLE
[RFC] Serializer use cases

### ISSUE THREAD

**Issue by elehcim** [cta-observatory/ctapipe#218]
After the last workshop, some common use cases to serialize output of algorithms where highlighted.
Here below a not-exhaustive list. Please add as comments other possible use cases or comments on them.
- To be able to save to a file a single container (the obvious one).
- If a list of containers is provided as input, merge them stacking horizontally the columns (a check on possible duplicates must be carried out and in case rename columns).
- If container has different telescope related quantities (like MC data), write on different streams including information about triggers and event id.
## DL1

For dl1, it could be useful to save calibrated image (this unfortunately does not fit on a fits table because of its possible variable length) along with -preliminary- parameters. These two data containers should be referenced to each other via obs_id and event_id.

**Comment by MaxNoe** [comment]
I think this is implemented now (at least 1 and 2).
