### ISSUE TITLE
Rename master → main

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2193]
After the next release, I am going to rename the master to main, just a heads up.

**Comment by nbiederbeck** [comment]
Please remember telling everyone about it :wink: 

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes

```
$ git branch -m master main
$ git fetch origin
$ git branch -u origin/main main
$ git remote set-head origin -a
```

**Comment by maxnoe** [comment]
> Please remember telling everyone about it wink

Github does that automatically when renaming the branch through the interface
