### ISSUE TITLE
CI Tests failing with Exit Code 143

### ISSUE THREAD

**Issue by RuneDominik** [cta-observatory/ctapipe#2218]
**Describe the bug**
Recently, some CI tests seemingly random fail with exit code 143 (probably killed via SIGABRT). Locally all tests complete without the problem.

**To Reproduce**
Run the CI e.g. on #2168 or #2138

**Expected behavior**
Tests should complete.

**Supporting information**
![CI_Summary](https://user-images.githubusercontent.com/22680504/212348204-be027feb-1944-485d-a6f4-b6cff9d40822.png)

![Screenshot from 2023-01-13 15-55-32](https://user-images.githubusercontent.com/22680504/212349976-7229b01f-76cb-40fb-816d-8c5a63e5bd9a.png)

**Additional context**
According to [this](https://github.com/actions/runner-images/issues/6709) issue this might mean that the CI exceeds the runners resources (e.g. 7GB RAM) or this is a problem with `ubuntu-latest`. Profiling the memory usage locally using [`mprof`](https://pypi.org/project/memory-profiler/) and simply running `mprof run pytest` results in a somewhat monotonic rise in usage reaching 7GB. It might be that the current masters memory usage is pushing the runners capacities and newer PRs simply reach the limit.

#### On current master:
![TestMaster](https://user-images.githubusercontent.com/22680504/212348544-20188977-1951-4991-b7a8-dd747f3dd0f4.png)

#### On #2168:
![TestNew](https://user-images.githubusercontent.com/22680504/212348793-6929fe0e-5391-492e-ac02-9ca837789fc8.png)

Quickly comparing this to `gammapy`'s without having the datasets downloaded shows that their memory is freed more often then `ctapipe`'s:

#### On current gammapy master:
![TestGammapy](https://user-images.githubusercontent.com/22680504/212349326-7bd2696f-93e5-41ea-ada1-6cbebc3bdb28.png)

**Comment by kosack** [comment]
this certainly looks like a memory problem - we quite recently ran memprof and it showed stable memory use around a few GB (still somewhat higher than gammapy due to the data sizes, but nothing like what you see here). So I suspect there is a regression.

**Comment by maxnoe** [comment]
These are the object counts after the last test has run:

```
.dict                       336613
list                       179640
function                   81750
tuple                      77713
weakref                    64178
builtin_function_or_method 49083
Float64Col                 42293
Quantity                   35714
QuantityColumnTransform    33407
cell                       20568
Path                       20130
CompositeUnit              17768
Int64Col                   13299
Float32Col                 10718
Angle                      10384
getset_descriptor          9867
Table                      9711
set                        9536
Int32Col                   8972
type                       8497
wrapper_descriptor         7602
Parameter                  7180
Description                6704
Column                     6693
TelescopeDescription       6019
CameraDescription          6019
MetaIsDescription          5958
method_descriptor          5682
Int16Col                   5631
method                     5360
CameraGeometry             5145
```

It seems somehow most of the subarray data is not cleaned up and also table readers (see all the column transforms) are sticking around

**Comment by maxnoe** [comment]
It's actuall 143, which for docker means the container got killed due to resource constraints. So it very certainly is a memory issue.
