### ISSUE TITLE
Move ctapipe-extras submodule.

### ISSUE THREAD

**Issue by mackaiver** [cta-observatory/ctapipe#222]
Hi,

right now the ctapipe-extras folder is a git submodule which is entirely non-optional for users.
I'd like to discuss whether it makes sense to move the ctapipe-extras thing into an external python dependency installable by pip. Or simply add the required files to a resources folder.

I think the latter solution is even simpler to handle.

**Comment by MaxNoe** [comment]
See https://github.com/cta-observatory/ctapipe-extra/pull/3

**Comment by MaxNoe** [comment]
ctapipe-extras is now a python module.

**Comment by kosack** [comment]
Now that ctapipe-extras is a module, you just need to clean up where it is used in ctapipe and make it a dependency, and that should be ok.

**Comment by mackaiver** [comment]
I agree. 👍
