### ISSUE TITLE
ExitStack is untested, because test is in wrong file

### ISSUE THREAD

**Issue by nbiederbeck** [cta-observatory/ctapipe#2224]
https://github.com/cta-observatory/ctapipe/blob/8a7a367dfe4a2f4e9bdf0e9bf774be29bf03b75f/ctapipe/core/tool.py#L614

**Comment by nbiederbeck** [comment]
This means, `ExitStack` is untested!

**Comment by maxnoe** [comment]
I am 100% certain I ran this test manually... something went wrong somewhere.
