### ISSUE TITLE
Remove `EventSource.from_config`

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2258]
**Please describe the use case that requires this feature.**

`EventSource.from_config` is not needed anymore (and since quite some time), since `EventSource(parent=self)` "just works™".

@FrancaCassol was confused about what the purpose is. Since it doesn't serve one anymore, we should remove that method.

**Comment by kosack** [comment]
It comes from the `traitlets.config` API:  you can either construct a `Component` by
1.  passing in trait arguments explicitly  `SomeComponent(param1=1, param2="x")
2. passing in a `traitlets.config.Config` dictionary `SomeComponent(config=config)`
3. referencing a parent Configurable, that already has or will have a config loaded later `SomeComponent(parent=self)` where `self` is a `Component` or `Tool` (which both inherit from `triaitlets.config.HasConfig`)

The constructors are overloaded to support all three methods, but generally you should not mix them. E.g. if you specify `config=x` you should not specify `parent=x`.
