### ISSUE TITLE
Need to pin numpydoc version

### ISSUE THREAD

**Issue by Tobychev** [cta-observatory/ctapipe#2262]
**Describe the bug**
Trying to build docs with versions from `environment.yml` fails with following error
```
Exception occurred:
  File "/local/home/tb273079/miniconda3/envs/cta-dev/lib/python3.9/site-packages/numpydoc/numpydoc.py", line 34, in <module>
    raise RuntimeError("Sphinx 4.2 or newer is required")
```

**To Reproduce**
1. make doc

**Expected behavior**
docs should build

**Comment by kosack** [comment]
Any idea why this is not causing a test failure?

**Comment by maxnoe** [comment]
I guess @Tobychev installed / update single packages locally and in the CI starting from a fresh env we always get it with a correct dependency resolution
