### ISSUE TITLE
HillasIntersection produces error on badly reconstructed events

### ISSUE THREAD

**Issue by gschwefer** [cta-observatory/ctapipe#2264]
**Describe the bug**
When using the `HillasIntersection` algorithm, the direction reconstruction in the nominal frame can lead to reconstructed values of `src_fov_lat` with an absolute value greater than 90 degrees. This occurs when there are few telescope images (i.e. usually 2) in the reconstruction which have very close values of `hillas_psi` . The ellipses are then almost parallel and the major axes intersect at great distances from the camera center.

 When this results in `src_fov_lat` with an absolute value greater than 90 degrees, `SkyCoord` here

https://github.com/cta-observatory/ctapipe/blob/6c4bd9cc73d0845feb7f8abd08dcc45993edb67f/ctapipe/reco/hillas_intersection.py#L228-L230

throws a corresponding error. In `ctapipe-process`, the processing will be aborted.

**Expected behavior**
Since these events are so badly reconstructed that they will be thrown away for any analysis anyway, this case may as well result in an invalid reconstruction for the event. This would allow processing to continue. I'm open to better solutions, that just seems like the easiest.

**Additional context**

For the `HillasReconstructor`, this is only a problem if all reconstructed major axes are _exactly_ aligned.

**Comment by gschwefer** [comment]
If the fix suggested above is ok, I could open a pull request very quickly. Is this something that should also go in a unit test?

**Comment by maxnoe** [comment]
> , this case may as well result in an invalid reconstruction for the event. 

Yes, that's the right thing to do. Check the value of `src_fov_lat` and if it is larger than 90 degrees return the invalid result container.

The actual threshold could probably be even lower than the threshold that triggers the error in astropy and fov_lon and fov_lat aren't really different in this regard.

Maybe check for 45 degrees in both?

**Comment by gschwefer** [comment]
Yes, sounds good

**Comment by kosack** [comment]
This looks related to #1200 as well
