### ISSUE TITLE
Latest documentation seems to be rendered wrong

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#2296]
**Describe the bug**

Notebooks in the docs now include extra fields for each cell for some reason (change in _nbsphinx_?)

**To Reproduce**
Runs in the CI, generated by Sphinx

**Expected behavior**

Correctly rendered notebooks in sphinx

**Supporting information**

For example:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/11677812/228281243-4e104ed1-281f-41d2-a521-339302ec4298.png">

**Comment by maxnoe** [comment]
Doesn't seem to be nbsphinx=0.9 (which released recently), I downgraded to 0.8 and it's the same...

**Comment by maxnoe** [comment]
Sorry, had to `make clean`. With 0.8 it indeed looks correct.

**Comment by maxnoe** [comment]
Fixed in https://github.com/cta-observatory/ctapipe/pull/2266
