### ISSUE TITLE
on_pixel_picked function of interactive CameraDisplay gets called for all displays

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#2355]
**Describe the bug**

As found by Vincent:

When multiple CameraDisplays are plotted on different Axis objects, each with a registered "pick_event" callback, they all seem to respond to the same "pick_event", so clicking one display moves the selected pixel on the other and the callback is called once per instance.  

They should be independent. 

**To Reproduce**

```py3
from ctapipe.visualization import CameraDisplay
from ctapipe.instrument import CameraGeometry

import matplotlib.pyplot as plt

class MyCameraDisplay(CameraDisplay):
   def on_pixel_clicked(self, pix_id):
       print(f"MyCamera: {pix_id=} has value {self.image[pix_id]:.2f}")

fig, ax = plt.subplots(2,2)
geom = CameraGeometry.from_name("NectarCam")

disp1 = MyCameraDisplay(geom, ax=ax[0,0])
disp1.enable_pixel_picker()
disp2 = MyCameraDisplay(geom, ax=ax[0,1])
disp2.enable_pixel_picker()

plt.show()
```

When clicking a pixel in either CameraDisplay, both get updated and the `on_pixel_picked()` method gets called twice

**Expected behavior**

Each display can be clicked independently

**Supporting information**
If applicable, add screenshots, logs, or a traceback to help illustrate the bug.

**Additional context**

The relevant line is probably:
https://github.com/cta-observatory/ctapipe/blob/623ac86a3bb08613f670d1757914a6ead940d421/ctapipe/visualization/mpl_camera.py#L269

Which should set the callback on this instance, not in general.

**Comment by maxnoe** [comment]
I think I already commented somewhere, that we should have `enable_pixel_picker` take a callback function, not via the currently intended inheritance

This would also solve this issue
