### ISSUE TITLE
Common File store for DL1 images at least (CCin2P3)

### ISSUE THREAD

**Issue by jacquemier** [cta-observatory/ctapipe#239]
As announced  during bootcamp I have verified the status of CCIN2P3 web server that we asked (for small dataset file for test) few years ago.

Unfortunately CCIN2P3 has delete this server because there was no traffic on it (they sent us a mail before)
It could take long time to recreate it.

So any other solution are welcome

**Comment by MaxNoe** [comment]
@kosack  we have a webserver, right?
