### ISSUE TITLE
`get_hdf5_datalevels` seems broken

### ISSUE THREAD

**Issue by Tobychev** [cta-observatory/ctapipe#2450]
**Describe the bug**
The function `get_hdf5_datalevels` reports no data levels for files that clearly contains data level data

**To Reproduce**
```
import ctapipe.io as cio
import pathlib
g_meeting_file_name = pathlib.Path("../2023 Oct F2F/2023-10-datapipe-workshop-material/data/model_training/gamma_20deg_0deg___cta-prod5b-lapalma_desert-2158m-LaPalma-dark_cone10.alpha_train_cl_merged.DL2.h5")
cio.get_hdf5_datalevels(g_meeting_file_name)
```
returns `()`

**Expected behavior**
That it returns at least `DataLevel.DL1_PARAMETERS`

**Comment by maxnoe** [comment]
Checking with `ctapipe-fileinfo`, the same file claims to contain images, which is also wong. Seems the merge file didn't adapt the metadata correctly to the options it was given.

**Comment by maxnoe** [comment]
Ok, so `get_hdf5_datalevels` actually inspects the groups present in the hdf5 file, not the metadata.

**Comment by maxnoe** [comment]
Aha! The error here is a missing type check.

`get_hdf5_metadata` expects a `tables.File` as argument. In your example, you gave a `pathlib.Path`, which also happens to have a `.root` attribute, but which is the empty string, so all checks `foo in h5file.root` return False:


```
In [4]: f = tables.open_file("../data/datapipe_workshop/model_training/gamma_20deg_0deg___cta-prod5b-lapalma_desert-2158m-LaPalma-dark_cone10.
   ...: alpha_train_cl_merged.DL2.h5")

In [5]: get_hdf5_datalevels(f)
Out[5]: (<DataLevel.DL1_PARAMETERS: 6>, <DataLevel.DL2: 7>)
```

**Comment by Tobychev** [comment]
Aha! I think a secondary issue is how things are presented in the docs, where `get_hdf5_metadata` comes just after the generic read and write functions that _do_ take just a filename.
