### ISSUE TITLE
Docs failing

### ISSUE THREAD

**Issue by Hckjs** [cta-observatory/ctapipe#2535]
Docs are failing in #2529 with sphinx version 7.3.5. This [sphinx change](https://github.com/sphinx-doc/sphinx/pull/12203) results in [this issue](https://github.com/sphinx-doc/sphinx/issues/12300), due to the [functions we use in the sphinx gallery conf](https://github.com/cta-observatory/ctapipe/blob/bd7da6a5a00d52a5795afc306bb2debe66bded5e/docs/conf.py#L167)

**Comment by maxnoe** [comment]
This is actually a great change! It will let us fix local build times being high using `sphinx-autobuild` etc...

**Comment by AA-Turner** [comment]
See: https://github.com/sphinx-gallery/sphinx-gallery/issues/1286

A
