### ISSUE TITLE
ImPACT tests failing on main

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2546]
**Describe the bug**
After merging the ImPACT branch, a test of it fails on main (at the moment only on macos, but doesn't look mac specific)

**Comment by maxnoe** [comment]
E.g. here: https://github.com/cta-observatory/ctapipe/actions/runs/8819610819/job/24211266186?pr=2544

**Comment by maxnoe** [comment]
and here: https://github.com/cta-observatory/ctapipe/actions/runs/8819581133/job/24211172507

**Comment by gschwefer** [comment]
Ok, interesting. The easiest thing would be to just raise the tolerance on the assert_allclose a bit. But then when I test it locally the current tolerance is far more than enough, so I wonder what the actual issue is here...
