### ISSUE TITLE
`Provenance().add_input_file()` should take product id

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2571]
**Please describe the use case that requires this feature.**

Add the moment, the provenance system only stores the path of an input file.

However, for CTAO data products used as input, the most important thing to store would actually be the product id of the reference metadata, not just the path.

**Describe the solution you'd like**
Optionally also store product uuid in provenance.

**Comment by kosack** [comment]
Would be useful to also add a nice helper function to extract the product_id from existing files.  In fact that could just be automatic: `add_input_file(path)` could call `get_product_id(path)`, and if it fails, emit a warning and continue as we do now without recording it.   That way it's more foolproof that the real product_id gets propagated
