### ISSUE TITLE
Check uniqueness of obs_id / event_id when merging files.

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2610]
**Please describe the use case that requires this feature.**

Processing on the GRID merged the same file multiple times resulting in later errors when joining tables.

**Describe the solution you'd like**

Check uniqueness of obs_id event combinations when merging files to prevent such issues at the point where the error happens.

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
