### ISSUE TITLE
Add nice __repr__ s to the reference metadata objects

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2649]
**Please describe the use case that requires this feature.**

The Reference metadata objects currently do not have reprs:

```
(Pdb) str(inputs[0]["reference_meta"].product)
'<ctapipe.io.metadata.Product object at 0x7f82685366d0>'
```

**Describe the solution you'd like**
Add reprs

**Comment by kosack** [comment]
Some have reprs, but it is not consistent.  Could just use the `_to_dict()` helper function in that directory as a general way.
