### ISSUE TITLE
Shouldn't a Tool's config be reset on initialize?

### ISSUE THREAD

**Issue by watsonjj** [cta-observatory/ctapipe#269]
Otherwise the Tool will use arguments set from a previous initialize, instead of resetting to default values. Personally, I believe the behaviour where the config is reset is more intuitive.

**Comment by MaxNoe** [comment]
I agree!

**Comment by kosack** [comment]
yes, sounds like a  good idea. Tool is still basically just a straight subclass of `traitlets.config.Application`, which doesn't have that behavior, but we can change it.

**Comment by MaxNoe** [comment]
I think it is pretty clear, that a Tool is meant to be a command line application and thus can only be run once.
