### ISSUE TITLE
conda pyhessio package is not compatible with ctapipe master branch

### ISSUE THREAD

**Issue by jacquemier** [cta-observatory/ctapipe#286]
The last commited version of pyhessio conmpatible with ctapipe master branch is [here](https://github.com/cta-observatory/pyhessio/commit/60b027713a94bf93349632a1b0718c5dbae0d503)

We need to rebuild the pyhessio conda package from this commit or to change ctapipe master branch to be comptabile with current pyhessio conda package.

**Comment by mackaiver** [comment]
Can we upload pyhessio to pypi and add it as an dependency to the setup.py? That way the version can be fixed. Also users don't have to manually install the package.

**Comment by jacquemier** [comment]
We decide to use anaconda cloud to fix the issue.
https://anaconda.org/cta-observatory/pyhessio
