### ISSUE TITLE
proposal to speed up algorithms that use pixel neighbor lists

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#346]
I did a study of why the image cleaning algorithm (tailcuts) is slower than I would like, and found the issue is how the neighborlist is stored and applied.  The following shows several implementations of the tailcuts algorithm, using different representations of the neighbor list.  (conclusion below)

![py36](https://cloud.githubusercontent.com/assets/11677812/23952037/6590128e-0990-11e7-800c-bf8d14c2ff9f.png)

The conclusion is that using a 2D boolean matrix for the neighbors and *numpy* operations is significantly faster than even a simple for-loop based C implementation (the *cython-opt* method is equivalant to a c for-loop method with compiler optimizations turned on). The reason is likely the vectorizability of operations and modern CPU features.  Using the following neighbor matrix instead of an adjacency list of pixel-ids seems to be the fastest improvement:

![unknown](https://cloud.githubusercontent.com/assets/11677812/23952136/bce23044-0990-11e7-935b-3b672ac4703d.png)

Using this will likely also allow for speedups of other algorithms.  I plan on implementing it directly in the code in a future pull-request.

Full study here:
https://github.com/kosack/ctapipe/blob/improve_cleaning_speed/examples/notebooks/speed_up_image_cleaning.ipynb

**Comment by kosack** [comment]
@watsonjj this could likely also speed up parts of the calibration that use nearest-neighbors. Though, it means some re-structuring of code that uses them.

**Comment by watsonjj** [comment]
I've seen this, and will test/implement it in the charge extraction techniques as soon as I have time.

**Comment by kosack** [comment]
Great, I'll modify the `CameraGeometry` class and the `image` module cleaning functions to use it, then you don't have to do much other than update your algorithms.

**Comment by kosack** [comment]
@watsonjj once  PR #360 is merged, you can use the `geom.neighbor_matrix` attribute to speed up your algorithms (see `image.tailcuts_clean` and `image.dilate` for examples).  It may also simplify some other code, since you no longer need to cache the camera geometries youself, you can just keep loading or calling `.guess`, which is much faster now and automatically caches previously constructed geometries.

**Comment by watsonjj** [comment]
@kosack I will try to look at this today. A problem I previously had with caching was if I was working with multiple files, as I was caching by telescope index. This is much nicer!
