### ISSUE TITLE
provide normalization option for CameraDisplay 

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#36]
CameraDisplay should have a friendly interface to set the normalization to e.g.  log(value), sqrt(value), etc.  Internally it can be done simply by using `self.pixels.set_norm(x)` and `self.cmap.set_norm(x)` where x is a `matplotlib.colors.Normalize` instance (e.g. `matplotlib.colors.LogNorm()`) 

Perhaps making this a attribute like `cmap` so that it works like this:

```python
disp = CameraDisplay(...)
disp.norm = "log"
disp.norm = "sqrt"

# or they can set it from an instance:
disp.norm = matplotlib.colors.LogNorm(vmin=0.1)
```

Alternately follow the matplotlib convention of using a function like `disp.set_norm(x)`

**Comment by MaxNoe** [comment]
No need for traditional getters and setters.

`matplotlib.collection.PatchCollection` has a `@property` norm.
