### ISSUE TITLE
Improving the NeighbourPeakIntegrator

### ISSUE THREAD

**Issue by watsonjj** [cta-observatory/ctapipe#363]
The new neighbor_matrix was recently added to the CameraGeometry class, which could potentially improve the speed of algorithms that require information about the neighbours to the pixel.

I have attempted to improve NeighbourPeakIntegrator by using the new neighbor_matrix, but the most obvious implementation using it is 10x slower than the original method using a list.

Below is a link to an IPython notebook containing a comparison between the old method and the new method. Can anyone find a better implementation of the algorithm that will improve the speed?

https://www.dropbox.com/s/omy60lnw3su6iy5/new_NeighbourPeakIntegrator.ipynb?dl=0

**Comment by ParsonsRD** [comment]
Hi, I think the problem here is that using the neighbour matrix you are allocating an array of size 1855 * 1855 * 30 * 1. i.e. more than 100 million entries.

I think no matter what you do with such long arrays the algorithm will be slow, simply due to the memory allocation and the filling of the array!

**Comment by kosack** [comment]
You shouldn't need to generate your own neighbor matrix, just use the one in the CameraGeometry (there is no reason to re-generate it).  it also should not have to be 4 dimensional - broadcasting rules should work fine.

**Comment by kosack** [comment]
It's actually maybe a good case for cython, since it's a complex operation that can easily be done with a loop.

**Comment by ParsonsRD** [comment]
Could we try using this as an example next week?

**Comment by kosack** [comment]
sure, it would be a nice example of cython maybe.

btw, to use cython in a notebook is really easy:

```
%load_ext cython
```

then any cell that starts with `%%cython` gets compiled automatically:

```python
%%cython

def cython_func(x):
    cdef int ii
    cdef double y = 0
    for ii in range(100):
         y += ii
    return y

**Comment by ParsonsRD** [comment]
Oh wow, I wish I knew that earlier :-)
