### ISSUE TITLE
CameraDisplay.update not very intuitive

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#37]
The `update` method of `CameraDisplay` only updates when `autoupdate == True`.

I think this is misleading and also does not allow the user to force an update if `autoupdate == False`.

Should we change `update` to always update and change our calls to:

```
if self.autoupdate:
    self.update()
```
?

**Comment by kosack** [comment]
yes, I fully agree! It was not well thought out to start with.  It should be possible to force an update via a call to `update()`, even if autoupdate is false.

I think I originally intended to have a function:

```
def _update(self):
    if self.autoupdate:
       self.update()
```
and then use that internally.  Then the public `update()` function always forces the redraw.
