### ISSUE TITLE
paranal.atmprof.fits.gz missing

### ISSUE THREAD

**Issue by ParsonsRD** [cta-observatory/ctapipe#396]
paranal.atmprof.fits.gz needed for atmospheric tables, currently not included in ctapipe-extras repository. @kosack I guess you have this file from testing this code right?

**Comment by kosack** [comment]
Have you updated recently? I got rid of ctapipe-extras as a submodule, and now it is an external pacakge (you need to do `conda install -c cta-observatory ctapipe-extra`.  You should delete the submodule if you still have it in your ctapipe directory.   The paranal file is in the new external package, but you should use `ctapipe.instrument.get_atmosphere_profile_functions` to read it (or use the `ctapipe.reco.ShowerMaxEstimator`, which I modified to use that function internally.  

We now can have any number of atmosphere profiles, as long as they are named "X.atmprof.fits.gz"
