### ISSUE TITLE
What does n_channels mean?

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#40]
Could you explain what the channels mean for the cameras? 
These are  not the pixels, right? Is it lowgain / highgain?

**Comment by jacquemier** [comment]
Yes, I confirm,channels mean lowgain/highgain 

----- Mail original -----

De: "Maximilian Nöthe" <notifications@github.com> 
À: "cta-observatory/ctapipe" <ctapipe@noreply.github.com> 
Envoyé: Mercredi 11 Novembre 2015 00:55:08 
Objet: [PUB][ctapipe] What does n_channels mean? (#40) 



Could you explain what the channels mean for the cameras? 
These are not the pixels, right? Is it lowgain / highgain?

**Comment by kosack** [comment]
Yes, "channels" generically refer to "data readouts" per pixel (front-end
signal processing + digitization), which in our cameras are associated with
different front-end amplifier gains that are used before digitization,
though in principle they could be used for other purposes. We have multiple
amplifiers to achieve a larger dynamic range in the hardware (except
FlashCam which uses a non-linear amplifier to compress the dynamic range)
