### ISSUE TITLE
Sphinx build broken if hessio not present

### ISSUE THREAD

**Issue by cdeil** [cta-observatory/ctapipe#42]
It's no longer possible to build the ctapipe Sphinx docs if hessio isn't present.
(Sphinx tries to `import hessio` and fails with an ImportError).

This also broke continuous integration:
https://gist.github.com/cdeil/7fe1706ed368f7e52c72#file-gistfile1-txt-L133
https://travis-ci.org/cta-observatory/ctapipe/jobs/90762905#L1017

Related: #22 and the efforts to improve hessio install by @jacquemier  and @MaxNoe .

What's the solution here?
Is `hessio` a required or optional dependency for `ctapipe`?

**Comment by jacquemier** [comment]
I finally manage to install pyhessio module during travis test.
So pyhessio is not a problem anymore for building ctapipe Sphinx docs .
But for information This test still failed because of 3 warnings, causing python command returns non zero value)
