### ISSUE TITLE
read_hessio.py Wrong number of bytes were read (635256 instead of 1560656)

### ISSUE THREAD

**Issue by jacquemier** [cta-observatory/ctapipe#44]
libhessio from hessioxxx displays an error at the tenth event with read_hessio.py and stops read_hession.py

Wrong number of bytes were read (635256 instead of 1560656)

**Comment by jacquemier** [comment]
This error seems to be in hessioxxx and not in our python code.
I'am trying to reproduce it without Python

**Comment by kosack** [comment]
I think that's normal. The test file I used was just a big (multi GB) file that I truncated to a few MB, so the last event is almost certainly corrupt.
