### ISSUE TITLE
Using ModuleNotFoundError breaks python 3.5 compatibility

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#443]
`ModuleNotFoundError` was only added in 3.6, before only `ImportError` was raised.

There are two possibilities:
* drop python 3.5 support
* Use `ImportError`, `ModuleNotFoundError` inherits from `ImportError`

**Comment by MaxNoe** [comment]
See #444

**Comment by kosack** [comment]
Should change to ImportError then.  I didn't realize `ModuleNotFoundError` wasn't compatible.  The builds pass for py3.5, but of course they are versioned from a git-repo, so that code is never called.
