### ISSUE TITLE
tailcuts_cleaning takes CameraGeomtry, hillas_parameters takes `pos_x`, `pos_y`

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#497]
I think this should be consistent

**Comment by kosack** [comment]
I think the reason was just that you can use the hillas algorithm for non-camera images as well (or at least cases where you haven't constructed a full CameraGeometry), but we could make it accept either.

**Comment by kosack** [comment]
A possibility is to also define a class like `CherenkovImage` that contains the image data + CameraGeometry and use that in all places where images are processed.  Though sometimes the "image" is really a "movie" if there is a time axis, and may also have multiple gain channels, etc  (I never could think of a good term).
