### ISSUE TITLE
What is the meaning of `data.trig.gps_time` for simtel MCs?

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#502]
Is this useable for coordinate transformations? E.g. does the Az, Alt transformed with this timestamp yield a meaningful Ra, Dec?

**Comment by kosack** [comment]
I think it's the timestamp of the start of the readout window (e.g. the time at which the central trigger asks the telescopes to read out from), so the waveforms should be defined from that point. It could be defined differently though.

**Comment by MaxNoe** [comment]
Reading simtel files, it seems to be the timestamp of the simulation
