### ISSUE TITLE
Why do CameraFrame and HorizonFrame need an `ArrayPointing`

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#505]
Transformation from Camera Coordinates to sky coordinates should only require the pointing of the single telescopes, or not?

**Comment by kosack** [comment]
I think the coordinate transforms are a bit backward and need reworking (see e.g. #416)

**Comment by ParsonsRD** [comment]
Short answer, they don't. However if they are defined here then a direct transformation can be performed all they way through all the systems. e.g. from camera directly to Horizon.

Agreed this needs restructuring though.

**Comment by MaxNoe** [comment]
Why does a transform from `CameraFrame` to `AltAz` need an `ArrayPointing`? 

The individual pointing of the Telescope should be enough.

**Comment by ParsonsRD** [comment]
Yes, it doesn't but some of the frames in between do. Currently the coordinates transform doesn't bypass any systems, such as the system centred on the nominal array pointing direction, but that is easy to change in the astropy structure.

**Comment by MaxNoe** [comment]
fixed in #896

**Comment by thomasgas** [comment]
Solved in #896
