### ISSUE TITLE
build_sphinx is the last failing test on travis.

### ISSUE THREAD

**Issue by jacquemier** [cta-observatory/ctapipe#54]
build_sphinx is the last failing test on travis.
It return none-zero value because of warnings, not error.
The easy solution is to remove '-w' option, but detect warning are clear advantages.
Does someone know how to remove this 3 warnings ?
[https://travis-ci.org/cta-observatory/ctapipe/jobs/113655229](url)

**Comment by jacquemier** [comment]
Resoved by #94

**Comment by jacquemier** [comment]
On my system there is no more sphinx warning.
But on travis, there are still some warnings.
- warnings came from Matplotlib:
```
"'Matplotlib is building the font cache using fc-list. This may take a moment"
-/home/travis/build/cta-observatory/ctapipe/astropy_helpers/astropy_helpers/sphinx/ext/docscrape.py:120: UserWarning: Unknown section Parameters:
  warn("Unknown section %s" % key)
/home/travis/build/cta-observatory/ctapipe/astropy_helpers/astropy_helpers/sphinx/ext/docscrape.py:120: UserWarning: Unknown section Returns:
  warn("Unknown section %s" % key)
/home/travis/build/cta-observatory/ctapipe/astropy_helpers/astropy_helpers/sphinx/ext/docscrape.py:120: UserWarning: Unknown section Example
  warn("Unknown section %s" % key)
/home/travis/build/cta-observatory/ctapipe/astropy_helpers/astropy_helpers/sphinx/ext/docscrape.py:120: UserWarning: Unknown section Note:
  warn("Unknown section %s" % key)
```


We must have a ctapipe that passes travis to facilitate code review and pull request.
I suggest to remove the "-w" sphinx option until we understand how to  supress these warnings.

Does it sounds good for you ?

**Comment by MaxNoe** [comment]
This warning is issued when matplotlib runs for the first time after  installation.
It searches for installed fonts in the system.
