### ISSUE TITLE
Drop support for python 3.5?

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#562]
Should we support only python 3.6+?  https://docs.python.org/3/whatsnew/3.6.html
The main advantages are mainly cosmetic, but make life a bit easier and the code perhaps cleaner. Any thoughts?

### easier (and faster) text formatting with f-strings:

```python
my_variable = 12.3
aligned = 0.2

print( f"The value of my_variable is {my_variable}, and aligned is {aligned:.03f}" )  
```

```
The value of my_variable is 12.3, and aligned is 0.200
```

as opposed to the <= 3.5  way with `str.format()`:
```python
print("The value of my_variable is {my_variable} and aligned is {aligned:.03f}"
    .format(my_variable=my_variable, aligned=aligned)")
```
The value of my_variable is 12.3, and aligned is 0.200

###  Underscores allowed for spacing in large numerical values:

```python
x = 1_000_000 * u.GeV
```

### variable annotations

Not used by the language directly, only during code checking or introspection, but still nice for readability in situations where it's not clear, or perhaps for use with the Container classes:

```python
class A:
    thelist : list = [1,2,3,4]
```

Note, function annotations were already supported in older version, and we use them sometimes in ctapipe (probably should use them more) e.g. 
```python
def myfunc(i:int, j:int, x:float) -> float:
   return x**(i+j)
```

**Comment by mackaiver** [comment]
Yes. Drop it.
