### ISSUE TITLE
Add support for masks back into hillas parameters

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#572]
After the change to the hillas parameters API, it's no longer possible to use a cleaning mask.

I think this should be added again, possibly by adding a `pixel_mask` kwarg.

**Comment by kosack** [comment]
There is already masking support in `CameraGeometry`.

```py3
masked_geom = geom[mask]

hillas_parameters(masked_geom, masked_pixels)
```

**Comment by kosack** [comment]
we could as you suggest add an option, but then the function starts to get much more complicated.
