### ISSUE TITLE
missing unit tests for pixel_likelihood.py

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#584]
https://codecov.io/gh/cta-observatory/ctapipe/src/5a2bc45412392e47d754586b72746b074dbd1466/ctapipe/image/pixel_likelihood.py

Several functions need unit tests:
* `poisson_likelihood()`
* `mean_poisson_likelihood_gaussian()`
* `chi_squared()`
* `_integral_poisson_likelihood_full()`

**Comment by StFroese** [comment]
Coverage is at 100% now. https://app.codecov.io/gh/cta-observatory/ctapipe/blob/master/ctapipe/image/pixel_likelihood.py
