### ISSUE TITLE
Containers do not inherit fields

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#648]

**Comment by dneise** [comment]
see also:
#649  and #650 

If you can fix it ... of course #650 is not needed.

**Comment by dneise** [comment]
They do inherit something ... 
![2018-02-16-151154_1920x1080_scrot](https://user-images.githubusercontent.com/8200858/36311523-d56f7a36-132b-11e8-94b1-4b95f416253a.png)

**Comment by MaxNoe** [comment]
See #651
