### ISSUE TITLE
Enforce particular Container inheritance rule

### ISSUE THREAD

**Issue by dneise** [cta-observatory/ctapipe#649]
There is a rule in the container Docu that says:
https://github.com/cta-observatory/ctapipe/blob/39cf9af6df8ffed682982aa40a0581d722db76a3/ctapipe/core/container.py#L85-L86

I think this rule should be "must not" and not "should not". Since devs who still do it, will have problems that take them long hours to debug. I think such strange limitations must be enforced and not only documented. 

I make a proposal how to do it in a PR

**Comment by MaxNoe** [comment]
See #648 , i think there is an easy fix

**Comment by dneise** [comment]
Very good. Then we do not need that strange rule anymore, do we?

**Comment by dneise** [comment]
will be closed by #648
