### ISSUE TITLE
Cleanup and structure examples

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#657]
I think we have too many examples in the base folder.

My proposol would be to have 3-5 basic examples that show the very basics to get started in the base folder and move anything else to subfolders to make them easier to find for people who look for certain things.

Right now, any newcomer won't really know where to start.

**Comment by kosack** [comment]
Sounds good. I think we also need to clean up those remaining examples as well.  The other question is how many should be notebooks vs python code (notebook are nicer for demos, but harder to test).

**Comment by kosack** [comment]
Many of the examples are simply plotting examples, so I suggest we make a plotting subdir, and perhaps remove the very old "brainstorm" and "obselete" directories.  The other option is to separate the examples into another package (like ctapipe-extras) but that may be confusing.

**Comment by kosack** [comment]
see also #739 : should have core examples as notebooks and have them render in Sphinx (as in GammaPy)

**Comment by kosack** [comment]
fixed for notebook examples in #941  Still have to do this for regular examples.
