### ISSUE TITLE
Structure of the instrument module

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#67]
In my opinion having classes for the instrument description might be a nicer interface.

The different loading and writing functions could then be class methods and be used like this:

``` python
from ctapipe.instrument import InstrumentDescriptiion

instrument = InstrumentDescription.from_hessio('/path/to/file')
instrument.to_fits('instrument.fits')
```

**Comment by kosack** [comment]
agreed. This same concept is mentioned in #49

**Comment by kosack** [comment]
Similar to your example, this is from the discussion in #49 :

```python
from instrument import OpticsDescription

od = OpticsDescription.from_file("test.eventio.gz")
od = OpticsDescription.from_metadata(obsid=123456, telid=56)
```
