### ISSUE TITLE
Issues with ctapy Demo

### ISSUE THREAD

**Issue by Sojourner92** [cta-observatory/ctapipe#708]
The ctapy.py demo in examples/brainstorm/misc_demos is flagging up a lot of issues in codacy. I've fixed most of its complaints but need the 'events.fits' file to test it. Does anyone have it, or should we just delete the example?

**Comment by kosack** [comment]
I think the events.fits file is any DL3 event file, so it should work with the data challenge data. 

However, the brainstorm code is unused even if sometimes still interesting.  At the  very least it shouldn't be checked for style. Either we drop it all, or exclude it from what pep8/pyflakes/flake8 check (in setup.cfg) and that will clean up many issues.

**Comment by kosack** [comment]
I'd say probably just remove the whole brainstorm directory, and I can always add that stuff to another repo.
