### ISSUE TITLE
Slack chat?

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/ctapipe#719]
I forgot to mention it during the ASWG meeting in Barcelona, but do you think it would be a good idea to set up a chat for rapid communication between users? Sometimes I want to have a quick chat with somebody but the only way is through email or opening an issue. I propose slack:

https://slack.com/

because it has a nice interface, it is successfully used in several of the collaborations I work for and if you do not have the app opened, you will get an e-mail with the message you got.

**Comment by dneise** [comment]
I never used slack, but I have a similar feeling that sometimes a quick chat might be just the thing we want. If currently unclear stuff is being asked in (private) emails, then I believe newbies like me could learn a lot by just following this chat.

**Comment by vuillaut** [comment]
Yes absolutely!
And I have been wondering the same about ASWG group.

**Comment by watsonjj** [comment]
I think we are in desperate need for something like this

**Comment by rlopezcoto** [comment]
if @kosack agrees, I can set it up and send the invitations around.

**Comment by mackaiver** [comment]
Maybe the invitation can go to the ASWG mailing list? Then anyone who is interested can join.

**Comment by kosack** [comment]
Sounds good to me - I have Slack installed, but have so far never had a use for it!

**Comment by bregeon** [comment]
Please go for it... Hopefully, CTAO will provide something for everyone at some point.

**Comment by moralejo** [comment]
​Hi,
​
On 25 April 2018 at 11:27, Karl Kosack <notifications@github.com> wrote:

> Sounds good to me - I have Slack installed, but have so far never had a
> use for it!
>
​fine for me too, the only question is whether we should make this move on
our own (i.e. ctapipe/DPPS & ASWG)  - Karl, wouldn't this be redundant with
Confluence, in case it is adopted in CTA at large? What is the status of
that?

Best regards,

Abelardo

-- 

Abelardo Moralejo Olaizola
Institut de Física d'Altes Energies
Tel : +34 931641662
Fax: +34 935811938
Avís - Aviso - Legal Notice - (LOPD) - http://legal.ifae.es

-- 
Avís -
Aviso - Legal Notice - (LOPD) - http://legal.ifae.es 
<http://legal.ifae.es/>

**Comment by watsonjj** [comment]
> Slack is free but in order to save the chat, (browse them, if I am not wrong) one needs to pay a per person per year fee. I am not sure CTA would like to do that, but I would definitely be happy. It's useful for ordered chat

On a free account a maximum history of 10,000 messages is kept, which is browsable and searchable. Slack could be used for minor direct messaging and conversations, but anything important that needs a permanent record of should still be placed on github.

**Comment by bregeon** [comment]
If CTAO doesn't want to pay for a full slack service, it could use an open source alternative like mattermost and have it's own servers. The use of a free slack site shall certainly be limited to casual chat and for nothing critical. It could still be worth to have a general site with different sub channels... As so many people seem to be interested

**Comment by rlopezcoto** [comment]
ok, so do we wait until you discuss it with CTAO @moralejo, @GernotMaier, @kosack?

**Comment by kosack** [comment]
As far as I know, CTAO is currently looking into purchasing the full Atlasssian suite, which includes something like this (Stride).  But I have no idea if there is a timescale for that, or even if it will be the accepted solution.  So I would say for now, having a Slack channel would be useful, and we can always migrate  to something official when we have it (the same goes for GitHub, TravisCI, etc)

**Comment by MaxNoe** [comment]
> As far as I know, CTAO is currently looking into purchasing the full Atlasssian suite, which includes something like this (Stride). 

Mmh. Any chance to go for GitLab / GitLab Mattermost?

**Comment by rlopezcoto** [comment]
ok, so I created the *ctapipe* team in slack. 
The access to slack is by invitation only, so I only sent the invitation to some people I have the e-mail of. Please drop me an e-mail (rlopezcoto@gmail.com) if you want to receive the invitation. Any team member can send these invitations so you can contact other members in the near future and feel free to invite anybody interested on ctapipe.
If @kosack or anybody else wants to make more publicity of the slack chat (sending an e-mail to the ASWG list, etc...), please go ahead.

**Comment by kosack** [comment]
I guess we can close this since it's set up! We can perhaps update the developer docs to show this as well.
