### ISSUE TITLE
Delete unused modules and scripts

### ISSUE THREAD

**Issue by mackaiver** [cta-observatory/ctapipe#72]
Hello,
I think it makes sense to start some clean up right now. I think there are some obsolete files we can delete.  
There are a lot of scripts and notebooks in the examples folder. Keeping them all up to date will be hard. Maybe we should concentrate on the main use case for now and just delete/move other stuff. 

Here is the output of the `vulture` tool to find unused functions and classes:

> ctapipe/_astropy_init.py:14: Unused attribute '_ASTROPY_SETUP_'
> ctapipe/_astropy_init.py:31: Unused function 'test'
> ctapipe/configuration/core.py:21: Unused attribute 'msg'
> ctapipe/configuration/core.py:237: Unused attribute 'optionxform'
> ctapipe/configuration/core.py:418: Unused function 'get_list'
> ctapipe/configuration/core.py:438: Unused function 'get_section_list'
> ctapipe/configuration/core.py:448: Unused function 'dynamic_class_from_module'
> ctapipe/configuration/tests/test_core.py:31: Unused variable 'res'
> ctapipe/coordinates/frames.py:67: Unused variable 'default_representation'
> ctapipe/coordinates/frames.py:84: Unused class 'TiltedTelescopeFrame'
> ctapipe/coordinates/frames.py:90: Unused variable 'pointing_direction'
> ctapipe/coordinates/frames.py:91: Unused variable 'telescope_location'
> ctapipe/coordinates/frames.py:95: Unused class 'GroundFrame'
> ctapipe/coordinates/frames.py:100: Unused variable 'observatory_location'
> ctapipe/coordinates/frames.py:103: Unused function 'camera_to_telescope'
> ctapipe/coordinates/frames.py:116: Unused function 'telescope_to_camera'
> ctapipe/core/__init__.py:12: Unused function 'component'
> ctapipe/instrument/CameraDescription.py:57: Unused function 'to_table'
> ctapipe/instrument/InstrumentDescription.py:15: Unused class 'Atmosphere'
> ctapipe/instrument/InstrumentDescription.py:19: Unused attribute 'rho'
> ctapipe/instrument/InstrumentDescription.py:20: Unused attribute 'thickness'
> ctapipe/instrument/InstrumentDescription.py:21: Unused attribute 'ext_coeff'
> ctapipe/instrument/InstrumentDescription.py:23: Unused function 'load_profile'
> ctapipe/instrument/InstrumentDescription.py:40: Unused function 'load_extinction_coeff'
> ctapipe/instrument/obsconfig.py:36: Unused function 'get_site_id_for_run'
> ctapipe/instrument/obsconfig.py:41: Unused function 'get_site_id_for_time'
> ctapipe/instrument/obsconfig.py:61: Unused attribute 'site_id'
> ctapipe/instrument/obsconfig.py:66: Unused attribute 'version_id'
> ctapipe/instrument/obsconfig.py:67: Unused attribute 'pixel_type'
> ctapipe/instrument/obsconfig.py:70: Unused attribute 'pix_z'
> ctapipe/instrument/obsconfig.py:72: Unused attribute 'focal_plane_offset'
> ctapipe/instrument/obsconfig.py:74: Unused function 'load_from_file'
> ctapipe/instrument/obsconfig.py:79: Unused class 'ArrayTriggerConfig'
> ctapipe/instrument/obsconfig.py:84: Unused class 'TelescopeTriggerConfig'
> ctapipe/instrument/obsconfig.py:101: Unused attribute '_optics'
> ctapipe/instrument/obsconfig.py:102: Unused attribute '_camera'
> ctapipe/instrument/obsconfig.py:121: Unused attribute 'tel_x'
> ctapipe/instrument/obsconfig.py:122: Unused attribute 'tel_y'
> ctapipe/instrument/obsconfig.py:123: Unused attribute 'tel_z'
> ctapipe/instrument/obsconfig.py:137: Unused property 'num_tels'
> ctapipe/instrument/obsconfig.py:154: Unused attribute 'optics_type'
> ctapipe/instrument/obsconfig.py:155: Unused attribute 'mirror_area'
> ctapipe/instrument/obsconfig.py:157: Unused attribute 'facet_x'
> ctapipe/instrument/obsconfig.py:158: Unused attribute 'facet_y'
> ctapipe/instrument/obsconfig.py:159: Unused attribute 'facet_z'
> ctapipe/instrument/obsconfig.py:160: Unused attribute 'facet_area'
> ctapipe/instrument/obsconfig.py:169: Unused attribute 'run_id'
> ctapipe/instrument/obsconfig.py:178: Unused attribute '_run_id'
> ctapipe/instrument/obsconfig.py:181: Unused attribute '_array'
> ctapipe/instrument/obsconfig.py:184: Unused attribute '_subarray'
> ctapipe/instrument/obsconfig.py:187: Unused attribute '_trigger'
> ctapipe/instrument/obsconfig.py:190: Unused class 'SimObsConfig'
> ctapipe/instrument/obsconfig.py:195: Unused attribute '_mc_run_id'
> ctapipe/io/array.py:29: Unused function 'tel_class_name'
> ctapipe/io/camera.py:86: Unused function 'from_file'
> ctapipe/io/data_container.py:12: Unused variable 'eventnumber'
> ctapipe/io/data_container.py:66: Unused property 'telescope_id'
> ctapipe/io/data_container.py:70: Unused property 'telescope_name'
> ctapipe/io/hessio.py:71: Unused attribute 'event_id'
> ctapipe/io/hessio.py:82: Unused attribute 'tels_with_trigger'
> ctapipe/io/hessio.py:85: Unused attribute 'gps_time'
> ctapipe/io/hessio.py:87: Unused attribute 'energy'
> ctapipe/io/hessio.py:88: Unused attribute 'alt'
> ctapipe/io/hessio.py:89: Unused attribute 'az'
> ctapipe/io/hessio.py:90: Unused attribute 'core_x'
> ctapipe/io/hessio.py:91: Unused attribute 'core_y'
> ctapipe/io/hessio.py:110: Unused attribute 'num_channels'
> ctapipe/io/mock.py:16: Unused function 'mock_event_source'
> ctapipe/reco/hillas.py:37: Unused variable 'HighOrderMomentParameters'
> ctapipe/reco/hillas.py:49: Unused function 'hillas_parameters_1'
> ctapipe/reco/hillas.py:108: Unused variable 'azwidth'
> ctapipe/reco/hillas.py:195: Unused variable 'hillas_parameters'
> ctapipe/tests/setup_package.py:1: Unused function 'get_package_data'
> ctapipe/tools/camdemo.py:30: Unused attribute 'cmap'
> ctapipe/tools/camdemo.py:58: Unused attribute 'image'
> ctapipe/tools/camdemo.py:62: Unused variable 'anim'
> ctapipe/tools/dump_triggers.py:34: Unused attribute 'description'
> ctapipe/tools/utils.py:47: Unused function 'get_all_main_functions'
> ctapipe/utils/datasets.py:47: Unused function 'get_example_simtelarray_file'
> ctapipe/utils/fitshistogram.py:95: Unused property 'bins'
> ctapipe/utils/fitshistogram.py:99: Unused property 'ranges'
> ctapipe/utils/fitshistogram.py:107: Unused function 'outliers'
> ctapipe/utils/fitshistogram.py:144: Unused function 'asFITS'
> ctapipe/utils/fitshistogram.py:293: Unused function 'draw2D'
> ctapipe/utils/fitshistogram.py:321: Unused function 'draw1D'
> ctapipe/utils/fitshistogram.py:328: Unused function 'interpolate'
> ctapipe/version.py:201: Unused variable 'major'
> ctapipe/version.py:202: Unused variable 'minor'
> ctapipe/version.py:203: Unused variable 'bugfix'
> ctapipe/version.py:206: Unused variable 'timestamp'
> ctapipe/version.py:207: Unused variable 'debug'
> ctapipe/version.py:212: Unused variable 'compiler'
> ctapipe/version.py:217: Unused variable 'cython_version'
> ctapipe/visualization/mpl.py:214: Unused property 'cmap'
> ctapipe/visualization/mpl.py:232: Unused property 'image'
> ctapipe/visualization/mpl.py:313: Unused function 'overlay_moments'
> ctapipe/visualization/mpl.py:390: Unused property 'values'
> ctapipe/visualization/tests/test_mpl.py:48: Unused attribute 'intensities'

**Comment by kosack** [comment]
Most of the stuff listed above are very importat to keep:

*  the configuration classes are new, and we need to migrate all tools to use them, so they should stay .
* The same for the coordinate tranform objects- they don't do much yet, but will be needed when somebody wants to make a reconstruction algorithm.
* `fitshistogram` is  already being using during this meeting to make lookup tables, so it needs to stay

Remember that right now we have 2 things: a framework where we start to make the tools needed to implement algorithms + the algorithms themselves.  We have only started the first part, 

However we should remove some things like one of the 2 implementations of hillas parameters, and *some* unused variables (often they are unused now, but we know they are needed).

Until we have some algorithms, it's hard to tell what is not required in the framework.
