### ISSUE TITLE
Container Cleanup

### ISSUE THREAD

**Issue by watsonjj** [cta-observatory/ctapipe#722]
I would like to use this issue to discuss some clean-ups to the Container classes that I would propose:

### inst
What is the plans for the inst container? Although it is currently marked as deprecated, it is the main accessor for instrument information in the pipeline.

### event.r0.tel[*].num_samples
Is this Field necessary? The same information can be obtained from the waveform shape.

### tels_with_data
Is this Field necessary? The same information can be obtained from, for example, `event.r0.tels.keys()`

### event_id and obs_id
Many of the containers (`r0`, `r1`, `dl0`, and even `MuonIntensityParameter`) contain these Fields, but it is a duplication of information. As it is an "event" container (it is updated per event), wouldn't this information be better located at the top level (`event.event_id`, or event perhaps `event.id`) instead of replicated in each sub-container 

### Methods inside containers
Containers such as `NectarCAMContainer` and `SST1MContainer` contain the methods to fill them (from the file) inside the container. This approach was fine to get a version of the EventSources into ctapipe, but I personally dislike approach. In my mind, it makes sense (and is easier to follow in the code) if all the reading from the file and filling of containers occurred in the EventSource class, and the containers.py was strictly kept to defining the containers and fields.

If anyone has some other cleanup suggestions to the containers, they are welcome in this thread.

**Comment by dneise** [comment]
I think this is a very good idea. 

Regarding the methods in containers, I think you are right, it was not a good idea to have these methods there.

**Comment by dneise** [comment]
```
class DL0CameraContainer(Container):
    trigger_type = Field(0o0, "camera trigger type")
```

Often the Field default value is `None`, here is it "octal zero" ... I assume this implies trigger types in ctapipe are typically expressed in base 8... Do I understand this correctly?

**Comment by dneise** [comment]
I never understood what the difference between `observation` and `event` was, e.g. in:
```
class R1Container(Container):
    obs_id = Field(-1, "observation ID")
    event_id = Field(-1, "event id number")
```

Now looking through the entire `containers.py` file I found:
```
class MuonRingParameter(Container):
    obs_id = Field(0, "run identification number")
    event_id = Field(0, "event identification number")
```
which seems to explain what the difference is. Is this naming scheme:

 * observation <-> run
 * event <-> event 

still open for discussion? 

In my understanding, events are either simulated or observed, so the term `observation` can be nicely used to distinguish from `simulation`. Imo the typical choice of "data and monte-carlo" as e.g. in "data monte-carlo mismatch" is not very precise... students coming into our field are often confused by these terms. Some people in my group therefore try to use "observation" and "simulation", which has a nice rhythm. However in that case it would not be wise to also use "observation" for "run"....

**Comment by dneise** [comment]
`MCEventContainer.h_first_int` I think `int` is too well known for `integer` to be used here as `interaction`

**Comment by dneise** [comment]
`R0CameraContainer.image` has this comment:

# to be removed, since this doesn't exist in real data and useless in mc

maybe we can remove it now? We should check where it is used. Btw. .. what is your best practice for searching if Field `foo` from sub-container `Bar` is used somewhere in the code? Searching for `Bar.foo` misses all places where this sub-container was assigned to a local variable?

**Comment by dneise** [comment]
`InstrumentContainer` is empty apart from a single field. We could remove it and instead of:
```
class DataContainer(Container):
    inst = Field(InstrumentContainer(), "instrumental information (deprecated")
```

do directly:
```
class DataContainer(Container):
    inst = Field(SubarrayDescription("MonteCarloArray"),
                     "SubarrayDescription from the instrument module")
```

**Comment by watsonjj** [comment]
@calispac 

> Could this be replaced by something of this kind:

One could instead do:
```
for event in event_source('file.format')
    for tel_id, event in event.r0.tels.items():
         print(event)
         print(tel_id)
```

which is currently supported in the current api.

Regarding your last point, that is a much bigger api change. I can see many benefits in the low-level Containers, but once you get to DL2 (I think), the concept of individual telescopes disappear and you have a single reconstructed event. I think it will be a lot simpler to continue to have the tel dict in each of the low-level containers.

**Comment by calispac** [comment]
> One could instead do:

Great did not even realized this !

**Comment by kosack** [comment]
> never understood what the difference between observation and event was, e.g. in:

Please read the CTA glossary! `obs_id` is what in the past was called the `run_id`, but since the concept of `runs` no longer exists, it is just an observation id number. It does not, however, need to be in the event container since it's technically metadata, but sometimes it's nice to have it there if you combine multiple events, which we do when analyzing monte-carlo.  E.g. we loop over many MC runs, write out data, and then merge them into one file, in which case, its useful to keep the obs_id so we can trace the event back to a file.  The event_id is reset to 0 for each MC run.

**Comment by kosack** [comment]
> InstrumentContainer is empty apart from a single field. We could remove it and instead of:

Yes, this is an open issue already - the `InstrumentContainer` is deprecated and will be removed, but there is still a question as to where we then get the `SubarrayDescirption` from. For now, it could just be an attribute of the EventSource (which currently only fill it on the first event, which wouldn't work), but in the future it will have a dedicated class to load it, since it may come from a DB, or other place, if it's not in the file.  I can't find the issue where I described this, but I'll try to locate it... oBviously it needs updating.

**Comment by kosack** [comment]
> I also think that it can be quiet annoying to have a tel_id per data level. I suppose this is mandatory if somehow between data levels one telescope can be dropped from the pipeline. If not could we simply looping through the events like this :

Yes, that is the reason for it - you lose telescopes at each data level, e.g. ones that cannot be reconstructed, etc.

**Comment by kosack** [comment]
For the `tels_with_data` field, I agree we could remove that, but it makes the code much less readable, so I'd suggest just making it a *property* that returns `set(tel.keys())`.  

Also, originally I had thought there may be a case where `tels_with_data` is a subset of `tel.keys()`.  That will of course happen if e.g. we have 2 cleanings running at once (which we absolutely will do), but the it's probably up to the developer to keep track of them, so I'd say this use case id not valid.

**Comment by watsonjj** [comment]
> For now, it could just be an attribute of the EventSource (which currently only fill it on the first event, which wouldn't work)

I think it should be possible to have the `SubarrayDescirption` description filled at the EventSource initialisation (before looping through the events begins) with a little re-write of HessioEventSource. Do you see a problem with that?

**Comment by kosack** [comment]
>  Do you see a problem with that?

No sounds good to me! Note that I think in pyhessio, I think you do need to still fill an event though (I may be wrong about that), but that could be hidden to the user.

**Comment by kosack** [comment]
Here is what I suggest for the `SubarrayDescription` (and the same goes for the `MCHeaderContainer`, which is not a per-event data, but rather header info, so should be removed from the event structure):

- modify all `EventSources` to provide access to header info (e.g. a subarray and simulation attribute)
- for now, keep the old InstrumentContainer filled,  but mark it as deprecated - a separate Issue/PR can be made to refactor all code that used it.  I would like to change most of the algorithms to explicitly take only the part of the instrument info they need, e.g. you'd pass a SubarrayDescription to the constructor of a Reconstructor, just like you now pas only the CameraGeometry to hillas_parameters, etc. I'd prefer that to passing the `EventSource` to algorithms, which should not happen.  We will need to think a bit about how to do that correctly

**Comment by watsonjj** [comment]
> Here is what I suggest for the `SubarrayDescription`

Great, thats exactly the approach I was going to use. Similarly for other Fields I suggested for removal, I will create properties that return the value from its updated location with a deprecated message

**Comment by watsonjj** [comment]
> For the tels_with_data field, I agree we could remove that, but it makes the code much less readable, so I'd suggest just making it a property that returns set(tel.keys()).
> 
> Also, originally I had thought there may be a case where tels_with_data is a subset of tel.keys(). That will of course happen if e.g. we have 2 cleanings running at once (which we absolutely will do), but the it's probably up to the developer to keep track of them, so I'd say this use case id not valid.
> 
> EDIT: I remember why we want tels_with_data - it must be Field if you want to write it to a file, and you absoluitely want to write this to an output file (or at least some translation of it, e.g. to a bit pattern). So it does need to be there as a Field - I already use it in many outputs to debug or to sub-select telescopes.

@kosack I just noticed your edit here.

I'm concerned `tels_with_data` is a potential source of confusion in its current form, and is one of the main reasons to start this clean-up discussion.

I think the information inside `tels_with_data` should always match `tel.keys()`. 

I have just realised that is not currently the case when specifying `allowed_tels` for HESSIOEventSource, and instead all the telescopes are read and stored inside `tel` irregardless if they are in `allowed_tels`. Is there a reason for this? This could be extra confusing when some people prefer to access the telescopes via this method:

```python
for event in event_source('file.format')
    for tel_id, r0_camera_event in event.r0.tels.items():
         print(r0_camera_event)
         print(tel_id)
```

Another handling of `tels_with_data` in the current version that I think is a mistake is that it is filled for all calibration levels on file reading, while the `tel` container is empty until calibration is performed. And if we fixed this so that `tels_with_data` is filled at the corresponding calibration level, we would need to make sure its reset to an empty set on reading the next event.

If you truly cannot see a way `tels_with_data` can be changed from a `Field` to an `@property`, then we should make sure we address these discrepancies.

**Comment by MaxNoe** [comment]
I would also opt for removing all abbreviations, so

* `obs` → `observation`
* `sim` → `simulation`
* `tel(s)` → `telescopes` or `telescope_events` 
* `inst`  → `instrument`

Defining the containers as `ArrayEvent` and `TelescopeEvent` might also be usefull and more clear.

**Comment by MaxNoe** [comment]
>  `tels_with_data` Is this Field necessary? The same information can be obtained from, for example, event.r0.tels.keys()

Agreed this is unncecessary redundancy. But maybe we should provide properties for those for convienience?

```
    @property
    def triggered_telescoeps(self):
        return list(self.telescope_events.keys())
    
    @property
    def num_samples(self):
        return self.r0.shape[1]
```

**Comment by dneise** [comment]
I think “convenience“ properties may easily create confusion.

One person iterates over .keys() the other over triggered_telescopes. A reader might easily think, these are two different things without looking one abstraction layer deeper.

I think there is more harm than good in that.

Also, when one starts to introduce these convenience properties in one place, why not also in another. The logic, when it is okay to add a convenience property and when not is hard to explain in my opinion.

I believe the smaller an interface, the less likely it is to mess it up. (Another reason to remove these fill_from_event methods, that I introduced earlier, they increase the interface in a surprising way)

**Comment by MaxNoe** [comment]
I would argue that these convenience methods add important semantics that Make code more readable. 

`n_samples` tells much more than `r0.shape[1]`

**Comment by kosack** [comment]
> Agreed this is unncecessary redundancy. But maybe we should provide properties for those for convienience?

Again, remember that the list of triggered telescopes needs to be a field in output files, so we need to think about how to preserve that  - if it is not a Field, it cannot be written out.

**Comment by kosack** [comment]
>  have just realised that is not currently the case when specifying allowed_tels for HESSIOEventSource, and instead all the telescopes are read and stored inside tel irregardless if they are in allowed_tels. Is there a reason for this? This could be extra confusing when some people prefer to access the telescopes via this method:

That was not how it worked in the original `hessio_event_source` code, and shouldn't be how it works now - the `HESSIOEventSource` should only read the requested telescopes - that speeds up I/O quite a bit. So I think we can then assume `allowed_tels` matches `tels_with_data`, and we can probably remove `r0.tels_with_data`.  However, I do want the ability to write out a telescope list to the resulting HDF5 (or other format) file when writing the event list. It's critical for making selections later on telescopes.

**Comment by kosack** [comment]
I'll open an issue to correct that

**Comment by kosack** [comment]
> Furthermore, the dl1 container never had a tels_with_data field.

It probably should. Especially if we start to generate more than one DL1 container (or DL1a?) when we do multiple cleanings/parametersizations for the algorithms that need it. In that case the list of telescopes that survived cuts will be algorithm-dependent, and we need to write out that list for each event.

**Comment by kosack** [comment]
That brings up another possible container refactoring: we are missing containers for the output image parameters (Hillas, muon, etc).  That might be best to be seaprate from the DL1 container, but it's still DL1 data... perhaps renaming `dl1` to  `dl1a`, and parameters derived from it, `dl1b`?

For DL1b, it's also not clear to me how to structure it so that we can support multiple parameter sets: do we have a Map of parameters per algorithm-name? e.g. `dl1a['hillas_standard'].tel[i].hillas.phi`? or some other structure?

**Comment by watsonjj** [comment]
> That brings up another possible container refactoring: we are missing containers for the output image parameters (Hillas, muon, etc). That might be best to be seaprate from the DL1 container, but it's still DL1 data... perhaps renaming dl1 to dl1a, and parameters derived from it, dl1b?
> 
> For DL1b, it's also not clear to me how to structure it so that we can support multiple parameter sets: do we have a Map of parameters per algorithm-name? e.g. dl1a['hillas_standard'].tel[i].hillas.phi? or some other structure?

I'm not sure we gain much by splitting it into dl1a and dl1b. As an alternate suggestion: `dl1.tel[i].image` `dl1.tel[i].parameters['hillas']` `dl1.tel[i].parameters['muon']`.

**Comment by watsonjj** [comment]
> In that case the list of telescopes that survived cuts will be algorithm-dependent

Ah, thats probably why it would be good to have dl1a and dl1b, disregard my last comment

**Comment by dneise** [comment]
> Please read the CTA glossary!

I did not find the term `observation` in the CTA glossary.

**Comment by maxnoe** [comment]
I think most of this has been addressed over the years, the main open points are discussed in #1165
