### ISSUE TITLE
Verify coordinates, particularly that the  Hillas Phi angle is correct for all arrays

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#737]
(this issue came from #723): It seems the Phi angle is 180 deg different depending on North or South arrays, and the core position is not always where I would expect it to be.  I would expect Phi to either be random, or align with the asymmetry of the shower (ideally).  This probably implies better descriptions of all coordinate systems, including any extra sign flips, or x/y-swaps needed to go from camera coordinates to ground coordinates.

Below are plotted the Hillas vectors from each telescope (after a rough cleaning), using `examples/plot_array_hillas.py`:

A LaPalmaRefSim MC: The vectors seem to intersect
![image](https://user-images.githubusercontent.com/11677812/39201470-7246addc-47ef-11e8-812b-c2bbd9e32d6b.png)

A standard Prod3b MC:
![image](https://user-images.githubusercontent.com/11677812/39201608-d77f771a-47ef-11e8-91c0-98de3be262da.png)

**Comment by mackaiver** [comment]
Needs to be checked again after cleaning up hillas code

**Comment by maxnoe** [comment]
I will close this issue, please reopen with an example where this goes wrong if this is still an issue
