### ISSUE TITLE
Move some notebooks to the docs

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#739]
Since sphinx can both execute and display Jupyter notebooks (via https://nbsphinx.readthedocs.io/), it might be nice to select some of our notebook examples to include in the main docs (or write some better ones). That way they both appear in the documentation, and are executed during the TravisCI build, so we can check for errors (similar to what is described manually in #724)

**Comment by kosack** [comment]
A nice example of this can be found in the [HESS GPS documentation](http://docs.gammapy.org/dev/notebooks/hgps.html)

**Comment by STSpencer** [comment]
One thing that would be useful is links to examples from function references, i.e. like [matplotlib](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.subplots_adjust.html#matplotlib.pyplot.subplots_adjust)

**Comment by kosack** [comment]
> One thing that would be useful is links to examples from function references, i.e. like matplotlib

I'm not sure if that's possible with the Jupyter Notebook extension to Sphinx, but perhaps there is some option to link the code? I haven't tried it out yet.

**Comment by MaxNoe** [comment]
THis was done some time ago.
