### ISSUE TITLE
Apparent conflict between new xmax code and new vpython example

### ISSUE THREAD

**Issue by STSpencer** [cta-observatory/ctapipe#761]
Trying to run the first cell in vpython_display.ipynb returns the error:

> AttributeError: 'HessioFile' object has no attribute 'get_mc_shower_xmax'

This appears to be a result of changes to hessioeventsource.py .

**Comment by mackaiver** [comment]
You need to make sure you have pyhessio version >= 2.1 installed. The dependencies have been updated.

**Comment by kosack** [comment]
yes, since the dependencies have changed, you must update your pyhessio package, or run 

```
conda env update -n <env name> environment.yml
```
