### ISSUE TITLE
Hillas parameters selecting instead of masking.

### ISSUE THREAD

**Issue by mackaiver** [cta-observatory/ctapipe#780]
Hillas parametrization behaves differently when selecting pixels instead of masking them. I find this to be surprising. Is this intentional? 

I opened a PR to show a test case.

**Comment by mackaiver** [comment]
Alright. I fixed the test. I made a copy paste error.

**Comment by MaxNoe** [comment]
This is due to a bug in `CameraRotation.__getitem__` which only happens when there is a camera rotation, see #782
