### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by cdeil** [cta-observatory/ctapipe#8]
@kosack – We should release early and often.

So I've added a 0.1 milestone for Friday next week (July 3).

This is a test release where I want to see if making the source tarball works and things like accessing the right version of cta-extra data from a stable release. It will not be advertised to anyone.

IMO it's not important to have any features ready by then, although having direction reco working by the end of next week would be nice.

**Comment by kosack** [comment]
That sounds good to me. I will try to also add all of my example code somewhere, and clean up some of the docs.  If I have time, I'll also look into and example of packaging+interfacing C code.

**Comment by cdeil** [comment]
@kosack – Sorry I didn't have time to work on `ctapipe` at all this week.

I still think it's useful to make a release for checking / practice.

Do you want to do it or should I? (if there's no issues it only takes ~ 1 hour to do it and some basic checking, but usually with the first release there's some things, like missing files because of the MANIFEST file or whatever ...)
Here's some notes I have for Gammapy how to make a release: https://gammapy.readthedocs.org/en/latest/development/index.html#make-a-gammapy-release

**Comment by cdeil** [comment]
@kosack – Any chance you can make a 0.1 release before the PyGamma15 workshop for ctapipe and maybe even make `pip install ctapipe` and / or `conda install ctapipe` work?

**Comment by kosack** [comment]
I can probably do that, but the project may soon move to being semi-private (due to the Project Office decisions today), so that may cause me some problems. I'll try to at least make a release of what we have. Ideally I'd like it on a separate conda channel

**Comment by MaxNoe** [comment]
Are you saying, that CTA just decided that the analysis software for CTA will be closed source?

**Comment by kosack** [comment]
No, It will almost certainly still be open-source (I will strongly push for that), but the development and distribution may be centralized (e.g. we may be required to abandon github + pypi, etc, and use a system installed at the PO like GitLab + a specialized conda channel).  Therefore a simple "pip install" may not work if we can't upload things to the public pypi.  It would still be fairly open, though it's not clear if they want us to start with a private repo or not. It all depends on what is drafted in the consortium agreement by lawyers.

**Comment by cdeil** [comment]
Closing this old issue now. Looks like there have been releases (or at least tagged versions) of ctapipe in the past.
