### ISSUE TITLE
`event.pointing` not filled

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/ctapipe#806]
The container `event.pointing` does not seem to be filled when reading simtel files.
I might take care of it later but I can't right now.

```
from ctapipe.io import event_source
from ctapipe.utils import get_dataset

source = event_source(get_dataset('gamma_test_large.simtel.gz'))
event = next(iter(source))
event.pointing[0].altitude, event.pointing[0].azimuth
```

returns
```
(<Quantity nan rad>, <Quantity nan rad>)
```

**Comment by kosack** [comment]
Probably we need to rethink this anyhow, since events do not have pointing information, rather each telescope does (and there is no guarantee all telescopes point in the same direction). Therefore, we should only store the pointing per telescope.

**Comment by vuillaut** [comment]
I see, you are right, this is certainly not where pointing should be stored.
Then maybe plainly removing this container would be better, it is a bit confusing to users I think.

**Comment by kosack** [comment]
I'll close this -I added another issue to remove the pointing structure, as suggested
