### ISSUE TITLE
use event.pointing correctly

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#807]
Since there is no event pointing info, only per-telescope, we should remove `event.pointing` from the standard container structure. see #806

**Comment by MaxNoe** [comment]
`event.pointing` is a map of `telescope_id` -> `TelescopePointingCointainer`, we discussed in dortmund that we want to move the pointing information there.

Maybe it should also be a container with a subfield `tel`?

**Comment by kosack** [comment]
Ah yes, I think I was confusing it with the old pointing container that only contained a single position. It seems now it is closer to correct. Yes, for consistency, the Map should probably be `event.pointing.tel[tel_id]`

**Comment by kosack** [comment]
I updated the title and now the task should be:

- update this to contain the pointing info for all telescopes
- fix EventIOEventSource (and HESSIOEventSource) to fill it correctly
- use it wherever pointing is needed (get rid of anywhere that uses `event.mcheader.run_array_direction`)

**Comment by dneise** [comment]
Sounds rather machanical work, i.e. pretty doable. Anybody working on this?

**Comment by maxnoe** [comment]
This is implemented now, I think through #1163
