### ISSUE TITLE
mapping for gain-channels?

### ISSUE THREAD

**Issue by dneise** [cta-observatory/ctapipe#818]
Would it be good to define the mapping for the gain channels in `waveforms`? 
I.e. something like `{'low-gain': 0, 'high-gain': 1}` ?

**Comment by MaxNoe** [comment]
@kosack proposed using an enum here:

https://github.com/cta-observatory/ctapipe/pull/683/files#diff-722d37cc1260e3557284e9056a2d9f3cR18

**Comment by watsonjj** [comment]
Solved by #1093
