### ISSUE TITLE
why make develop?

### ISSUE THREAD

**Issue by dneise** [cta-observatory/ctapipe#819]
Why do we recommend doing `make develop` (which hiding that the command actually is only `python setup.py develop`) and not `pip install -e .`?

[Some people](https://stackoverflow.com/a/19048754/1532474) seem to think the latter should be used. 
Some people think [there is no big difference](https://stackoverflow.com/questions/30306099/pip-install-editable-vs-python-setup-py-develop)

**Comment by kosack** [comment]
I'm happy either way - you can replace it with "pip install -e ." (or conda develop?) The main point of the make target was just that I couldn't remember the correct command each time :-)

**Comment by mackaiver** [comment]
We use `pip install -e .`
