### ISSUE TITLE
Calibration coefficients look wrong for Prod3

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#82]
Reading the peds and gains using `pyhessio`  like this:

```python
peds = pyhessio.get_pedestal(tel_id)[0]
gains = pyhessio.get_calibration(tel_id)[0]
plot(peds, gains, 'r+')
```

Works for Prod2 files:
![pedsgains_prod2](https://cloud.githubusercontent.com/assets/11677812/13990686/81d8db04-f115-11e5-9e2a-b81980887262.png)

But for Prod3 files you get 2 distinct distributions of pedestals and gains:

![pedsgains](https://cloud.githubusercontent.com/assets/11677812/13990931/711ab82c-f116-11e5-8ef0-fb404deda093.png)

Looking at it in image space, here is what you get when applying the coefficients, which looks like every other pixel has the wrong calibration (implying mixing of the two gain channels):

![withcalib](https://cloud.githubusercontent.com/assets/11677812/13990788/ea2d8f10-f115-11e5-9310-e04b5abdddb1.png)

And the raw data

![withoutcalib](https://cloud.githubusercontent.com/assets/11677812/13990789/ea31c1de-f115-11e5-856d-2e8a8913a5ac.png)

**Comment by kosack** [comment]
The problem appears to be that the gains for channel 0 and 1 are mixed in Prod3.  In Prod2 there is onyl one gain channel, so perhaps that is why they are not mixed.    This was noticed also by @moralejo  who then commented out the code (I reenabled it, but with a command-line switch, since it is not really a problem, just in the reading)

/cc  @jacquemier

**Comment by jacquemier** [comment]
Bug corrected with pyhessio v0.5.4 (commit 61570cd5117d4822bcee182ccb8dff2eb18ddfa2)

**Comment by jacquemier** [comment]
PROD3 with pyhessio v0.5.4
![prod3](https://cloud.githubusercontent.com/assets/13165509/14011848/f246d72e-f1a1-11e5-833d-c7f7dcbb0958.png)

**Comment by moralejo** [comment]
The change related to the command-line switch in read_hessio_single_tel
does not work for me:

    parser.add_argument('', '--calibrate', action='store_true', help='apply
calibration coeffs from MC')

It seems it does not like the first (empty string) argument. It works if I
add there anything which is not already used by other switches.

A.



On 23 March 2016 at 16:43, Karl Kosack <notifications@github.com> wrote:

> The problem appears to be that the gains for channel 0 and 1 are mixed in
> Prod3. In Prod2 there is onyl one gain channel, so perhaps that is why they
> are not mixed. This was noticed also by @moralejo
> <https://github.com/moralejo> who then commented out the code (I
> reenabled it, but with a command-line switch, since it is not really a
> problem, just in the reading)
>
> /cc @jacquemier <https://github.com/jacquemier>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cta-observatory/ctapipe/issues/82#issuecomment-200401106>
>



-- 

Abelardo Moralejo Olaizola
Institut de Física d'Altes Energies
Tel : +34 931641662
Fax: +34 935811938
Avís - Aviso - Legal Notice - (LOPD) - http://legal.ifae.es

-- 
Avís - Aviso - Legal Notice - (LOPD) - http://legal.ifae.es

**Comment by kosack** [comment]
strange - I had the same problem but thought I had checked in a fixed version. I'll fix it now.

**Comment by kosack** [comment]
it seems the fix is in there already - you probably just need to sync your fork and update (or do `git pull cta-observatory master` to merge in the changes)

**Comment by moralejo** [comment]
Hi,

On 29 March 2016 at 10:49, Karl Kosack <notifications@github.com> wrote:

> it seems the fix is in there already - you probably just need to sync your
> fork and update (or do git pull cta-observatory master to merge in the
> changes)
>
Yes, I did precisely git pull cta-observatory master... After which I got
the calibration back, but could not run it unless I made the above
mentioned change.

Should that first argument of parser.add_argument  be really empty?

A.



> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cta-observatory/ctapipe/issues/82#issuecomment-202782307>
>



-- 

Abelardo Moralejo Olaizola
Institut de Física d'Altes Energies
Tel : +34 931641662
Fax: +34 935811938
Avís - Aviso - Legal Notice - (LOPD) - http://legal.ifae.es

-- 
Avís - Aviso - Legal Notice - (LOPD) - http://legal.ifae.es

**Comment by kosack** [comment]
Sorry, I just noticed I hadn't accepted the pull request (from myself!) I'm still getting used to this system. It should be there now.  The fix was just to remove the blank argument. 

In any case, we should switch to using ctapipe.config instead of argparse directly, but that's a future change

**Comment by moralejo** [comment]
It works now, thanks!

On 29 March 2016 at 11:02, Karl Kosack <notifications@github.com> wrote:

> Sorry, I just noticed I hadn't accepted the pull request (from myself!)
> I'm still getting used to this system. It should be there now. The fix was
> just to remove the blank argument.
>
> In any case, we should switch to using ctapipe.config instead of argparse
> directly, but that's a future change
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cta-observatory/ctapipe/issues/82#issuecomment-202787137>
>



-- 

Abelardo Moralejo Olaizola
Institut de Física d'Altes Energies
Tel : +34 931641662
Fax: +34 935811938
Avís - Aviso - Legal Notice - (LOPD) - http://legal.ifae.es

-- 
Avís - Aviso - Legal Notice - (LOPD) - http://legal.ifae.es
