### ISSUE TITLE
Why is image two dimensional?

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#822]
the `DL1CameraContainer.image` is a 2d array, that can contain multiple images (e.g. for ASTRI).

Why is that? Shouldn't be `DL1` be always a single image?

**Comment by watsonjj** [comment]
A dimension per channel (hi gain, low gain). Should become a 1D array when gain selection has been implemented (see #683).

**Comment by watsonjj** [comment]
Solved by #1095
