### ISSUE TITLE
Magic number in Hillas reconstructor

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#829]
https://github.com/cta-observatory/ctapipe/blob/5e71b43c9d11a41e09442e2f02347529a26eae85/ctapipe/reco/HillasReconstructor.py#L195-L197

In the HillasReconstructor, two times the magic quantity 0.1 m appears

**Comment by mackaiver** [comment]
We decided to put the value in a variable and give a expressive name.
 https://github.com/cta-observatory/ctapipe/blob/e7152482461d1f386f3a998e6ac567e21bcb93f7/ctapipe/reco/HillasReconstructor.py#L200

**Comment by MaxNoe** [comment]
Is this 0.1m a valid value for all cameras?

In FACT that would half the camera radius, not "just a bit away. Same goes for the sst's.

Pinging @kbruegge, @kosack
