### ISSUE TITLE
How to add LST low level calibration test resources?

### ISSUE THREAD

**Issue by pawel21** [cta-observatory/ctapipe#838]
I wonder about how to test code in ctapipe.
To test my code (low level calibration for LST) I need at least two file:
1) 1 fits file ~ 30 MB
2) File with events ~ 2 GB.

Should I use `ctapipe-extra`? Aren't files too big?

**Comment by MaxNoe** [comment]
Yes, the vent file is too big. 

You should try to produce a smaller file with just a couple of events. Like 5 or 10.

Then you can add those to `ctapipe-extra`

**Comment by MaxNoe** [comment]
I Think this issue is about LST measured data not simulations and there are several small prod3b files included for testing in ctapipe

**Comment by MaxNoe** [comment]
LST low level calibration is no longer in scope of ctapipe, this  is handled in ctapipe_io_lst and cta-lstchain
