### ISSUE TITLE
Add members to organisation

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#840]
Here at the LST Bootcamp, many people working on ctapipe are not yet in the organisation.

@kosack or @mackaiver  could you add people who write here?

- [x] @pawel21
- [x] @FrancaCassol
- [x] @moritzhuetten
- [x] @AlySpoly
- [x] @LukasNickel
- [x] @noahhdf
- [x] @FrancescoGSaturni 
- [x] @jay3guru

**Comment by mackaiver** [comment]
added

**Comment by moritzhuetten** [comment]
Hi

**Comment by AlySpoly** [comment]
Can you add also me? Thank you!

**Comment by FrancescoGSaturni** [comment]
Hi, can I be added please? Thanks! :)

**Comment by noahhdf** [comment]
I‘m sure @LukasNickel want‘s to be added as wells

**Comment by tysaito2008** [comment]
Could you please add me as well? Thank you.

**Comment by mackaiver** [comment]
all added.

**Comment by jay3guru** [comment]
Hi, please can you add men. Thank you

**Comment by damgreen** [comment]
Please add me as well. Thank you!

**Comment by jay3guru** [comment]
Hello, please if you can add me. Thank you

**Comment by MaxNoe** [comment]
please contact anyone in this orga if you want to be added, for now, closing
