### ISSUE TITLE
Use a plug-in system for Factories?

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#844]
- right now the Factories are somewhat fragile (depend on order of  imports)
- would be nice to have a nicer convention for plugins for things like  IO sources, etc, that could even be in separate packages  (e.g. ctapipe-magic or ctapipe-hess packages would install readers  for those telescopes).

Similar things exist for other large python frameworks, so there is probably a nice way to do this

**Comment by MaxNoe** [comment]
Done.
