### ISSUE TITLE
Implement a method in SubarrayDescription to detect array layout name

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#847]
similar to the camera and optics lookup tables, just need a method to
turn an array layout into a standard array name. Probably we can just
support Prod4 layouts? or even Prod3 if we want to be complete.

**Comment by maxnoe** [comment]
We should not introduce more guessing than we already have.

We should implement ways of *setting* it. Not guessing it from random input data files.

**Comment by maxnoe** [comment]
We now assign array name via configuration or from simtel metadata, closing
