### ISSUE TITLE
Make the example  and test data auto-downloadable, like gammapy

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#849]
- remove from `ctapipe_resources`
- make a command  `ctapipe download test-data --version=0.3`
- if version is omitted, latest version is downloaded
- use the In2p3 server (for now) to store the data sets in versioned subdirs - this is accessible from wget or using the astropy download tools

**Comment by maxnoe** [comment]
This was solved (minus the download command, which I am not sure we need)
