### ISSUE TITLE
look into using traitlets for configuration and provenance data

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#85]
`traitlets.config` looks reasonable for a system to configure classes using config files or command-line args, which may be better than using argparse.  We'd just need a json to FITS header function to write them to output files for provenance data:

http://traitlets.readthedocs.org/en/stable/config.html

Might  be worth making a prototype to see if it meets our needs.

**Comment by jacquemier** [comment]
json config file does not contain user command line options, which are also needed for data provenance I guess.
traitlets.config.loader.Config contains both,  command line options and configuration file options.
I propose a traitlets.config.loader.Config to FITS header function to write Class configuration to output files for provenance data.
