### ISSUE TITLE
get rid of tels_with_data, and rely only on the Map keys

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#852]
The reason is that if you have multiple telescope algorithms being run in sequence (like cleaning), one may
drop a tel and not another, so you want to keep track of which telescopes survive at each data level/algorithm set, and not have to update it in 2 places.

This may require some re-thinking of how Containers are  organized.  

Would also be nice to have a standard function for turning a telescope list into a hit-pattern (boolean array or similar) for storage. 

### Use Case:
Imagine a pipeline chain that applies two sets of image cleaning (e.g. one for reconstruction and one for gamma-hadron selection).  In the reconstruction cleaning, 8 telescopes survive and are passed to the Reconstuctor, but in the looser cleaning for discrimination, 15 telescopes survive that are passed to the GammaHadronSelector.  

Having a single top-level tels_with_data (at levels above Dl0, where it makes sense) causes problems for this method.

**Comment by watsonjj** [comment]
This addresses one of the topics mentioned in #722, and I think it would be a nice improvement.
