### ISSUE TITLE
cleanup where pointing info is stored

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#854]
Array pointing is meaningless given that telescoeps can have mispointing or divergent/slew pointing. This infois now in mcheader and in event.mc.tel[x], and not in pointing, so should remove the PointingContainer and clean up the others. Also decide where raw vs corrected pointing info goes (I guess DL0.tel.x has the raw pointing, and DL1.tel.x has the corrected pointing)

**Comment by maxnoe** [comment]
This was fixed for the stage1 tool #1163
