### ISSUE TITLE
eventio library

### ISSUE THREAD

**Issue by mackaiver** [cta-observatory/ctapipe#860]
I want to discuss which eventio library do we want to use. There is `pyhessio` and the pure python library prepared by @dneise @MaxNoe  dubbed `pyeventio`

Some work is going on here: https://github.com/dneise/ctapipe/pull/2

Options are:

- [ ] Support both forever
- [x] Choose one over the other now
- [ ] Support both and check again in a year or so.

**Comment by jacquemier** [comment]
+1 If we can drop pyhessio.
As discussed with Max N, I have no problem with dropping pyhessio.

**Comment by mackaiver** [comment]
We will go with pyeventio. See https://github.com/fact-project/pyeventio/

**Comment by mackaiver** [comment]
@jacquemier great work with pyhessio btw. The pyeventio implementation was unittested against its output.
