### ISSUE TITLE
TableWriter improvements

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#863]
- is TableWriter sufficient?
- what formats to support? HDF5? Parquet? FITS-BINTABLE? 
- when writing out nested Containers, how to support writing out nested structures:
  *  recursively writing nested columns: probably breaks simply  pandas support (to check), but supported by (HDF5/PyTables/Parquet/JSON).  In that case you get columns with sub-columns in a nice structure  (e.g. `mc/energy`.  
  * flattening all sub-structure and appending the sub-container name to the column `mc_energy`. This works well with pandas and astropy Tables and FITS bintables, but requires special work to implement
 * both
 * neither (require users to explicitly write out each sub-Container)

**Comment by maxnoe** [comment]
I think with the improvements made in #1163 we can be pretty happy about the table writer as of now.
