### ISSUE TITLE
Also publish to PyPI

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#865]
While having a conda package is nice, I always think that this ought to be a second step to make it easier to install for conda users.

The first step should be to put it on PyPI.

**Comment by mackaiver** [comment]
Connected to #849

**Comment by MaxNoe** [comment]
Is anyone opposed to upload 0.7.0 to pypi? 

I would than make changes to .travis.yaml so that new versions will be automatically deployed. I need a first manual upload to get an API token just for ctapipe

**Comment by MaxNoe** [comment]
Ping @kosack

**Comment by maxnoe** [comment]
Done
