### ISSUE TITLE
Remove duplicate HillasParameters implementations. 

### ISSUE THREAD

**Issue by mackaiver** [cta-observatory/ctapipe#866]
As the title says. Right now we have 4 or 5 hillas implementations. I suggest to choose one of them.

**Comment by vuillaut** [comment]
I approve.
From my tests, 4 and 5 never fail while 1, 2 and 3 sometimes fail for some parameters (`nan` value returned).

**Comment by mackaiver** [comment]
We decided we need a test using some 'true' listed values. Also checking for all quadrants.

@MaxNoe mentioned he has some code doing that already in the toy-eventsource. 

We want to keep number implementation number 5 (cov, eigen)

**Comment by vuillaut** [comment]
Hi.
How would the true values computed in the first place?

Why implementation 5?

You may find a notebook to compare the different implementation of `hillas_parameters` in ctapipe there:
https://github.com/cta-observatory/cta-benchmarks/blob/master/hillas_parameters.ipynb

The results for `skewness` and `psi` are quite different.

**Comment by MaxNoe** [comment]
Because it's the most readable and runtime is not largely different (50% from slowest to fastest)

**Comment by MaxNoe** [comment]
> The results for skewness and psi are quite different.

Just minus signs and rotations by 180°, so no real different, there is a unit test in ctapipe showing this.

**Comment by vuillaut** [comment]
Ok thank you for the explanations @MaxNoe !

**Comment by MaxNoe** [comment]
Or not rotations but different domains of the angle. So some functions return [-pi, pi], which is not really helpful, as only a 180° range is meaningfull, and some use different domains with a width of 180°.

And the sign of skewness depends on the orientation of psi
