### ISSUE TITLE
Make a data flow diagram

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#868]
similar to the old CalibDataFlow:

**Comment by kosack** [comment]
![image](https://user-images.githubusercontent.com/11677812/49736684-14895b80-fc8b-11e8-8ccd-f478491e0123.png)

**Comment by Tobychev** [comment]
I think you've basically done this now with that diagram you put in the use case google doct, right @kosack ?

**Comment by kosack** [comment]
yes, I think we can close this for now.  We might want to make a simplified one for the documentation at some point, but that will come when we update the docs to include how to run the standard analysis
