### ISSUE TITLE
config=None, tool=None --> can this be removed?

### ISSUE THREAD

**Issue by dneise** [cta-observatory/ctapipe#869]
59 matches across 25 files

I think, `__init__`s with parameters `config=None, tool=None` are confusing. Although explicit is better than implicit, what does an explicit "parameter=None` tell me as a reader? Well, to me it says: 

> For this `parameter` we use some kind of default.

Which is an implicit information, no? When reading this, I always have to hold and think what this means. So I was wondering if we could remove this.

**Comment by mackaiver** [comment]
Yes.
