### ISSUE TITLE
Use real observation level height

### ISSUE THREAD

**Issue by thomasgas** [cta-observatory/ctapipe#879]
This seems to be hardcoded now for the Paranal and La Palma:

https://github.com/cta-observatory/ctapipe/pull/655#issuecomment-429386313

**Comment by mackaiver** [comment]
Will be added to the instrument configuration.

**Comment by maxnoe** [comment]
`SubarrayConfiguration` now uses an `EarthLocation` as reference point which is using the obs level from simtel array
