### ISSUE TITLE
Make a general test for EventSources

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#885]
Right now, the *X*EventSource tests are developed for each separate EventSource subclass, but it would be nicer to define exactly what all EventSources should do via a test, and then automatically test all of them. 

For example:
- check that an event is loaded and has reasonable values
- check that a SubarrayDescription is constructed correctly
- etc.

**Comment by maxnoe** [comment]
We only provide one event source with ctapipe now
