### ISSUE TITLE
convert event sources into plugins

### ISSUE THREAD

**Issue by dneise** [cta-observatory/ctapipe#890]
We decided to convert optional event sources into plug ins 
(also they have to be provided as conda packages)

we plan to use this plug in discovery mechanism

https://packaging.python.org/guides/creating-and-discovering-plugins/#using-naming-convention

So for example the zfits event source should be named `ctapipe_eventsource_zfits` or so.

**Comment by watsonjj** [comment]
Sounds like a nice improvement! I am onboard with this and thinking about how to adopt this for the TARGET file format...and hopefully make it more accessible

**Comment by MaxNoe** [comment]
done
