### ISSUE TITLE
Use `SkyOffsetFrame` for TelescopeFrame and NominalFrame

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#899]
It sound like we could just use astropy's `SkyOffsetFrame` for `TelescopeFrame` and `NominalFrame`, as these are basically AltAz Frames offset from the telescope pointing position or an arbitrary sky position.

**Comment by MaxNoe** [comment]
http://docs.astropy.org/en/stable/_modules/astropy/coordinates/builtin_frames/skyoffset.html#SkyOffsetFrame

**Comment by thomasgas** [comment]
Looks nice!

**Comment by MaxNoe** [comment]
Done in #896
