### ISSUE TITLE
HESSIOEventSource duplicates same MC informations for each event

### ISSUE THREAD

**Issue by jacquemier** [cta-observatory/ctapipe#906]
HESSIOEventSource fills DataContainer.mc.tel[tel_id].* for each event even though information never changes during the whole run.

File hessioeventsource.py method _generator

**Comment by watsonjj** [comment]
There may be some that don't change per event (so some cleanup would be a good idea), but some fields like `data.mc.tel[tel_id].photo_electron_image` do change per event.

**Comment by MaxNoe** [comment]
> even though information never changes during the whole run.

That's not true. E.g. the photo electron images changes per event. Also the simtel files have tracking per event, indicating that it might change.

**Comment by jacquemier** [comment]
I have never seen a simtel file where dc_to_pe and and pedestal change during the run. But I trust you and close this issue.

**Comment by MaxNoe** [comment]
> dc_to_pe and and pedestal change

That might be true. As far as I know these values come from the Monitoring data which is periodically written to the eventio files. (Not for every event, but for sure more than once per file)

This also seems to indicate that these values might change during a run, but I think the only safe thing would be to ask Konrad, if there are some values that although they are written multple times to the outpu file will not change during a run.
