### ISSUE TITLE
Do we have to delay complete initialization of extractors?

### ISSUE THREAD

**Issue by dneise** [cta-observatory/ctapipe#909]
I have a question. I was just looking at this piece here:

https://github.com/cta-observatory/ctapipe/blob/25b35cfb205757fb2c48d6a3e32d687e41f380a2/ctapipe/calib/camera/dl1.py#L209-L214

(this is not the only place such a delayed setup is performed, though)

This looks to me like a kind of 2nd delayed initialization of an extractor. This looks pretty scary to me, as I would have assumed an extractor, once it was handed over to me from one of our nice factories, is ready to extract whatever it should extract. Now I see, I should better ask an extractor whether it really feels up to the task yet, or needs any kind of additional information by me... 

How do you feel about this? Is this okay for you? Or should we try and fix this?

I believe this could be connected to something @kosack mentioned in Dortmund, which is that the Factories should maybe not look at the EventSource but on the SubArrayDescription, since the way one would like to extract most certainly depends on the Telescope...

Anyway ... looking a bit deeper, I found there is a nice helper function `check_neighbour_set` which raises an exception in case an extractor does require the neighbors, but does not know about them yet.. Certainly a nice function to have... but it seems not to be ever called. 

Also ... maybe we could just give the neighbors to all the extractors .. even if they do not need them. Thus making it mandatory to know about the camera geometry when trying to initialize an extractor for it...

What do you think?

**Comment by watsonjj** [comment]
As of #1155, the subarray is passed in initialization, and there in no delayed initialization for the neighbors
