### ISSUE TITLE
`calib` not python3 compatible

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#92]
Parts of the `calib` package are not python3 compatible.

For example in `ctapipe/calib/camera/mycam.py` 
```python
 if (len(sys.argv) < 1):
        print TAG, "Usage %s " % sys.argv[0]
        sys.exit(0)
```

Is missing the paratheses for the call to the `print` function.

**Comment by jacquemier** [comment]
Fixed  by  #93
