### ISSUE TITLE
plugin docu

### ISSUE THREAD

**Issue by dneise** [cta-observatory/ctapipe#926]
We should check if the current documentation about ctapipe plugins is sufficient and if not improve it.
Help is welcome.

**Comment by kosack** [comment]
I think it's basically non-existent, since we don't have any *true* plugins yet. We should switch to using a real system that loads plugins by package name, however.

**Comment by kosack** [comment]
see also #844 #890

**Comment by maxnoe** [comment]
We now have documentation for the plugin system and an example plugin in the repo
