### ISSUE TITLE
Remove get_shower_coordinates from CameraGeometry

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#934]
the `CameraGeometry.get_shower_coordinates()` code seems out of place - the instrument module is not for algorithms, but for describing the hardware, and I don't like mixing the concepts too much. 

I suggest we move this function elsewhere .  It seems to just be a coordinate transform, so could be a new `Frame` (it's just a rotated camera).  Or because it's only used by `image.get_timing_parameters() and `image.concentration()`, but nowhere else,  it could be a helper-function in the image module. 

https://github.com/cta-observatory/ctapipe/blob/1322e2fc32cfcaa6819cbcd10200caa4ac3801e6/ctapipe/instrument/camera.py#L494-L519

**Comment by MaxNoe** [comment]
Agreed. It might also be better es a more general method taking arbitrary x and y instead of the pixel positions
