### ISSUE TITLE
Drop HorizonFrame alias and just use astropy.coordinates.AltAz

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#949]

**Comment by thomasgas** [comment]
i agree

**Comment by thomasgas** [comment]
@MaxNoe do you plan to work on this?

**Comment by MaxNoe** [comment]
I don't know when I will have time for working on ctapipe again. At the moment I'm in the middle of starting a new  MC production for FACT.

**Comment by MaxNoe** [comment]
Closed by merging #975
