### ISSUE TITLE
ctapipe vs eventdisplay id

### ISSUE THREAD

**Issue by thomasgas** [cta-observatory/ctapipe#950]
I'm having a look at some files with ctapipe and a collegue is using EventDisplay. We are trying to see the differences in the cleaning and reconstruction event by event but the naming of the events are quite different.
so for me `event.count = 3`, while for her `Event = 1400`. 
for another event i have `event.count  = 11`, and she has `Event = 10200`. 

*Question*: how to we easily go from one event id to the other?

**Comment by MaxNoe** [comment]
Have a look not into count, this just counts the triggered event, but into `event.r0.event_id` and `event.r0.obs_id`.

**Comment by thomasgas** [comment]
thanks! 
event.r0.event_id and event.r0.obs_id are exactly what I was looking for.
Thanks @GernotMaier too!
