### ISSUE TITLE
About GainSelector class and gain_channel thresholds

### ISSUE THREAD

**Issue by misabelber** [cta-observatory/ctapipe#962]
Hello,
I've been trying to use the GainSelectorThresholds class from ctapipe.camera.calib and I found a couple of troubles that can make it a little inconvenient to use(or maybe I'm doing something worng, in that case I will be thankful to learn the proper way). 
The first thing is that as it is defined, it searches for samples in the waveforms over a certain threshold in PHE, but waveforms are given in dc counts, so if  you use the waveforms directly from the events (in simtel files, for example), it will give a wrong result.
 The default values  of the thresholds are read from ctapipe-extra/ctapipe_resources/gain_channel_thresholds.ecsv (and are in phe), and perhaps it would be better to have them in dc counts (or add a conversion factor for each camera definition). For example, for LSTCam 100 phe --> 4095 dc counts. 
The other issue is that the function pick_gain_channel searches for high gain waveform values purely larger than the threshold (>), but this will never happen, since samples will saturate at that exact value. The condition should be substitued by >=.
 Thank you very much!

**Comment by maxnoe** [comment]
I think this issue is fixed since a long time, please reopen if this still needs to be addressed.
