### ISSUE TITLE
Robust pixel neighbour calculation

### ISSUE THREAD

**Issue by watsonjj** [cta-observatory/ctapipe#963]
The pixel neighbour calculation may need revisiting. Currently it defines neighbours based on pixel separation. Right now, the defined separation seems to result in a different number of neighbours for different pixels on the CHEC-S camera. From examples/display_integrator.py:

![image](https://user-images.githubusercontent.com/17825673/52570941-e18f4f80-2e14-11e9-8e95-c71ebd9a7ff6.png)

I did not expect more than four neighbours for each pixel. Perhaps a more robust definition of a pixel neighbour should be implemented. Or perhaps it is fine to have N pixels within a separation to be defined as a neighbour. I will look into it.

**Comment by watsonjj** [comment]
This occurs due to the curved focal plane of the camera, which results in a changing pixel seperation with distance from the camera centre. The current neighbour definition does not account for this.

**Comment by MaxNoe** [comment]
I cannot reproduce this locally with the CHEC camera geometry that comes with ctapipe, can you provide a file where this happens?

**Comment by MaxNoe** [comment]
![n_neightbors_chec](https://user-images.githubusercontent.com/5488440/54520430-fbb6d300-4968-11e9-8235-532105b284b1.png)

**Comment by watsonjj** [comment]
Yeh sure. It occurs for the new CHEC geometry in Prod 4. An example simtel file can be obtained from this link:
https://www.dropbox.com/s/dlb05ntljpjhfil/run1.simtel.gz?dl=0

**Comment by MaxNoe** [comment]
My robust method results in this for the CHEC camera:

![neighbors_chec](https://user-images.githubusercontent.com/5488440/54522463-95807f00-496d-11e9-9a91-8368e11968f4.png)

Is this wanted?

**Comment by watsonjj** [comment]
No, usually we do count cross-module pixels as neighbours

**Comment by MaxNoe** [comment]
If I increase the tolerance to 0.35 I get the "correct" neighbors.

It's important that this threshold is smaller than sqrt(2) to not count the diagonals as pixels.

On the master it was `0.4`, but only evaluated on the central pixel, not for each pixel. This is why it broke for curved sensor plane.

**Comment by watsonjj** [comment]
I am happy to take a look at your alternative solution. I took the approach of defining the pixels in terms of row and columns, as that tends to be how we do this sort of thing in the CHEC group. The utility function for obtaining row and column could be useful to have (perhaps adapted to be more robust in a similar fashion as you have done for the neighbours).

**Comment by kosack** [comment]
> usually we do count cross-module pixels as neighbours

is there a reason for that? It's not clear to me if it is better or worse to count them. Has a study been done? Should be easy to check the resulting Hillas parameter differences.

**Comment by watsonjj** [comment]
Fixed by #1018
