### ISSUE TITLE
LST reader update

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/ctapipe#964]
Hi,

I would like to make a PR  for updating the LST reader. 
Some weeks ago, It was said that the camera readers should go out from ctapipe and be modified as plugin. Is this development foreseen in a short time  or can I go ahead with the PR for updating the reader?

Thanks

Franca

**Comment by MaxNoe** [comment]
The plugin system got merged and @dneise made a repository for the sst1m event source. LST reader could do the same.

**Comment by MaxNoe** [comment]
I extracted the relevant source code into this repo:
https://github.com/cta-observatory/ctapipe_io_lst

**Comment by FrancaCassol** [comment]
Thanks Max,

I will try to extract it  and then move it out of ctapipe

**Comment by MaxNoe** [comment]
@FrancaCassol I don't understand. I already did. This is what is in the repository I linked. And I also opened a ctapipe PR that removes it here #992 

I will now do the same for the nectarcam.

**Comment by MaxNoe** [comment]
Same for NectarCam here https://github.com/cta-observatory/ctapipe_io_nectarcam and https://github.com/cta-observatory/ctapipe/pull/993

**Comment by FrancaCassol** [comment]
> @FrancaCassol I don't understand. I already did. This is what is in the repository I linked. And I also opened a ctapipe PR that removes it here #992

Ok! I thought you were showing me an example :-)

Perfect. I will do a PR to update the LST reader in this new context, that in ctapipe is outdated
Thanks for the help
