### ISSUE TITLE
Allowed mirror types overly restrictive

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#983]
`OpticsDescription` raises errors, if mirror type is not one of `DC` or `SC`.

This is overly restrictive, as there are many more mirror types, even within CTA, I think the LST for example is a segmented parabolic mirror, not a Davies Cotton. 

FACT for example is a hybrid, in between Davies--Cotton and parabolic.

For what is is type actually used? I did not find anything.

**Comment by ParsonsRD** [comment]
Hi, yeah to be honest this information is not super useful, the optical configuration should not make any difference to our analysis. What would be useful though is just to store whether the telescope is single mirror or dual mirror. As if we introduce an "engineering camera frame" or something like that we will need to perform a flip of the camera for dual mirror optics at some point.

**Comment by MaxNoe** [comment]
To be really useful (I think the muon analysis needs it @AMWMitchell, @rlopezcoto),
one would also need information about the single tiles positions and shadowing, right?

**Comment by MaxNoe** [comment]
I started refactoring this in #982

**Comment by GernotMaier** [comment]
Completely irrelevant side note: the MST is also not a DC, but of 'intermediate' design with the intention to improve the timing compared to a pure DC design...

**Comment by MaxNoe** [comment]
Fixed in #982
