### ISSUE TITLE
Reco method cleaning

### ISSUE THREAD

**Issue by thomasgas** [cta-observatory/ctapipe#985]
I've an idea to clean a bit some stuff around. Each item is connected to the one above.

- [ ] Show 3D reconstruction method is better than 2D method (parallel pointing)
- [x] Make the 3D methos work also in divergent mode.
- [x] ~~Drop the 2D method. It also lacks of tests, so if we drop it we don't have to write them.~~

something else?

**Comment by watsonjj** [comment]
> Drop the 2D method. It also lacks of tests, so if we drop it we don't have to write them.

It seems a shame to delete it entirely. It could be nice to have an implementation of every reconstruction method available in ctapipe... could just be deprecated for the time being, until someone revitalises it?

**Comment by maxnoe** [comment]
We added tests for the hillas intersection. It seems to perform slightly worse, but is now tested and there is no real reason to remove it.
