### ISSUE TITLE
n_ vs num_ consistency

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#986]
We are inconsistent in variable names, the existing code is in favor of

`n_` for counters instead of `num_` for counters:

```
$ grep -RP --include='*.py' '[ ^,]num_.* ?= ?'  | wc -l
23
```

```
$ grep -RP --include='*.py' '[ ^,]n_.* ?= ?'  | wc -l
64
```

I also like `n_`  better for snake case variables.

**Comment by dneise** [comment]
`n_` is also a bit shorter...
